import ghidra.app.plugin.processors.sleigh
import ghidra.app.plugin.processors.sleigh.expression
import ghidra.app.plugin.processors.sleigh.symbol
import ghidra.xml
import java.lang
import java.util


class OperandSymbol(ghidra.app.plugin.processors.sleigh.symbol.SpecificSymbol):
    """
    Variable representing an operand to a specific Constructor
    """





    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDefiningExpression(self) -> ghidra.app.plugin.processors.sleigh.expression.PatternExpression: ...

    def getDefiningSymbol(self) -> ghidra.app.plugin.processors.sleigh.symbol.TripleSymbol: ...

    def getFixedHandle(self, hnd: ghidra.app.plugin.processors.sleigh.FixedHandle, walker: ghidra.app.plugin.processors.sleigh.ParserWalker) -> None: ...

    def getId(self) -> int: ...

    def getIndex(self) -> int: ...

    def getMinimumLength(self) -> int: ...

    def getName(self) -> unicode: ...

    def getOffsetBase(self) -> int: ...

    def getPatternExpression(self) -> ghidra.app.plugin.processors.sleigh.expression.PatternExpression: ...

    def getRelativeOffset(self) -> int: ...

    def getScopeId(self) -> int: ...

    def hashCode(self) -> int: ...

    def isCodeAddress(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def print(self, walker: ghidra.app.plugin.processors.sleigh.ParserWalker) -> unicode: ...

    def printList(self, __a0: ghidra.app.plugin.processors.sleigh.ParserWalker, __a1: java.util.ArrayList) -> None: ...

    def resolve(self, walker: ghidra.app.plugin.processors.sleigh.ParserWalker, debug: ghidra.app.plugin.processors.sleigh.SleighDebugLogger) -> ghidra.app.plugin.processors.sleigh.Constructor: ...

    def restoreHeaderXml(self, parser: ghidra.xml.XmlPullParser) -> None: ...

    def restoreXml(self, parser: ghidra.xml.XmlPullParser, lang: ghidra.app.plugin.processors.sleigh.SleighLanguage) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def codeAddress(self) -> bool: ...

    @property
    def definingExpression(self) -> ghidra.app.plugin.processors.sleigh.expression.PatternExpression: ...

    @property
    def definingSymbol(self) -> ghidra.app.plugin.processors.sleigh.symbol.TripleSymbol: ...

    @property
    def index(self) -> int: ...

    @property
    def minimumLength(self) -> int: ...

    @property
    def offsetBase(self) -> int: ...

    @property
    def patternExpression(self) -> ghidra.app.plugin.processors.sleigh.expression.PatternExpression: ...

    @property
    def relativeOffset(self) -> int: ...
