import ghidra.app.plugin.processors.sleigh.symbol
import java.lang


class SymbolScope(object):
    """
    A single scope of symbol names for sleigh
    """





    def __init__(self, p: ghidra.app.plugin.processors.sleigh.symbol.SymbolScope, i: int): ...



    def addSymbol(self, a: ghidra.app.plugin.processors.sleigh.symbol.Symbol) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def findSymbol(self, nm: unicode) -> ghidra.app.plugin.processors.sleigh.symbol.Symbol: ...

    def getClass(self) -> java.lang.Class: ...

    def getId(self) -> int: ...

    def getParent(self) -> ghidra.app.plugin.processors.sleigh.symbol.SymbolScope: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def id(self) -> int: ...

    @property
    def parent(self) -> ghidra.app.plugin.processors.sleigh.symbol.SymbolScope: ...
