import docking
import ghidra.app.plugin.core.functioncompare
import ghidra.framework.model
import ghidra.program.model.listing
import java.lang
import java.util


class FunctionComparisonProviderManager(object, ghidra.app.plugin.core.functioncompare.FunctionComparisonProviderListener):




    def __init__(self, __a0: ghidra.framework.plugintool.Plugin): ...



    def addProviderListener(self, __a0: docking.ComponentProviderActivationListener) -> None: ...

    def closeProviders(self, __a0: ghidra.program.model.listing.Program) -> None: ...

    @overload
    def compareFunctions(self, __a0: java.util.Set) -> ghidra.app.plugin.core.functioncompare.FunctionComparisonProvider: ...

    @overload
    def compareFunctions(self, __a0: ghidra.program.model.listing.Function, __a1: ghidra.program.model.listing.Function) -> ghidra.app.plugin.core.functioncompare.FunctionComparisonProvider: ...

    @overload
    def compareFunctions(self, __a0: java.util.Set, __a1: ghidra.app.plugin.core.functioncompare.FunctionComparisonProvider) -> None: ...

    @overload
    def compareFunctions(self, __a0: ghidra.program.model.listing.Function, __a1: ghidra.program.model.listing.Function, __a2: ghidra.app.plugin.core.functioncompare.FunctionComparisonProvider) -> None: ...

    def dispose(self) -> None: ...

    def domainObjectRestored(self, __a0: ghidra.framework.model.DomainObjectChangedEvent) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def providerClosed(self, __a0: ghidra.app.plugin.core.functioncompare.FunctionComparisonProvider) -> None: ...

    def providerOpened(self, __a0: ghidra.app.plugin.core.functioncompare.FunctionComparisonProvider) -> None: ...

    @overload
    def removeFunction(self, __a0: ghidra.program.model.listing.Function) -> None: ...

    @overload
    def removeFunction(self, __a0: ghidra.program.model.listing.Function, __a1: ghidra.app.plugin.core.functioncompare.FunctionComparisonProvider) -> None: ...

    def removeFunctions(self, __a0: ghidra.program.model.listing.Program) -> None: ...

    def removeProviderListener(self, __a0: docking.ComponentProviderActivationListener) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
