import ghidra.framework.options
import ghidra.program.model.listing
import ghidra.program.util
import java.lang


class AddressCorrelatorManager(object):




    def __init__(self, __a0: ghidra.feature.vt.gui.plugin.VTController): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    @overload
    def getCorrelator(self, __a0: ghidra.program.model.listing.Data, __a1: ghidra.program.model.listing.Data) -> ghidra.program.util.AddressCorrelation: ...

    @overload
    def getCorrelator(self, __a0: ghidra.program.model.listing.Function, __a1: ghidra.program.model.listing.Function) -> ghidra.program.util.AddressCorrelation: ...

    def getOptions(self, __a0: java.lang.Class) -> ghidra.framework.options.Options: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def readConfigState(self, __a0: ghidra.framework.options.SaveState) -> None: ...

    def setOptions(self, __a0: java.lang.Class, __a1: ghidra.framework.options.Options) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def writeConfigState(self, __a0: ghidra.framework.options.SaveState) -> None: ...
