import ghidra.feature.vt.api.main
import ghidra.program.model.listing
import java.lang


class SubToolContext(object):




    def __init__(self, __a0: ghidra.feature.vt.gui.plugin.VTPlugin): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDestinationFunction(self) -> ghidra.program.model.listing.Function: ...

    def getMatch(self) -> ghidra.feature.vt.api.main.VTMatch: ...

    def getSourceFunction(self) -> ghidra.program.model.listing.Function: ...

    def hashCode(self) -> int: ...

    def isDestinationCursorOnScreen(self) -> bool: ...

    def isSourceCursorOnScreen(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def destinationCursorOnScreen(self) -> bool: ...

    @property
    def destinationFunction(self) -> ghidra.program.model.listing.Function: ...

    @property
    def match(self) -> ghidra.feature.vt.api.main.VTMatch: ...

    @property
    def sourceCursorOnScreen(self) -> bool: ...

    @property
    def sourceFunction(self) -> ghidra.program.model.listing.Function: ...
