import ghidra.framework.plugintool.util
import java.lang
import javax.swing


class VersionTrackingPluginPackage(ghidra.framework.plugintool.util.PluginPackage):
    ICON: javax.swing.Icon = jar:file:/Applications/ghidra_9.2.1_PUBLIC/Ghidra/Features/VersionTracking/lib/VersionTracking.jar!/images/start-here.png
    NAME: unicode = u'Version Tracking'



    def __init__(self): ...



    @overload
    def compareTo(self, __a0: ghidra.framework.plugintool.util.PluginPackage) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDescription(self) -> unicode: ...

    def getIcon(self) -> javax.swing.Icon: ...

    def getName(self) -> unicode: ...

    @staticmethod
    def getPluginPackage(__a0: unicode) -> ghidra.framework.plugintool.util.PluginPackage: ...

    def hashCode(self) -> int: ...

    def isfullyAddable(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
