import java.lang


class ProjectedSequenceInfo(object):




    def __init__(self, __a0: int, __a1: int): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getProjectedIndex(self) -> int: ...

    def getSequenceIndex(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def projectedIndex(self) -> int: ...

    @property
    def sequenceIndex(self) -> int: ...
