import ghidra.feature.vt.api.main
import ghidra.program.model.address
import java.lang


class VTMatchInfo(object):




    def __init__(self, __a0: ghidra.feature.vt.api.main.VTMatchSet): ...



    def equals(self, __a0: object) -> bool: ...

    def getAssociationType(self) -> ghidra.feature.vt.api.main.VTAssociationType: ...

    def getClass(self) -> java.lang.Class: ...

    def getConfidenceScore(self) -> ghidra.feature.vt.api.main.VTScore: ...

    def getDestinationAddress(self) -> ghidra.program.model.address.Address: ...

    def getDestinationLength(self) -> int: ...

    def getMatchSet(self) -> ghidra.feature.vt.api.main.VTMatchSet: ...

    def getSimilarityScore(self) -> ghidra.feature.vt.api.main.VTScore: ...

    def getSourceAddress(self) -> ghidra.program.model.address.Address: ...

    def getSourceLength(self) -> int: ...

    def getTag(self) -> ghidra.feature.vt.api.main.VTMatchTag: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setAssociationType(self, __a0: ghidra.feature.vt.api.main.VTAssociationType) -> None: ...

    def setConfidenceScore(self, __a0: ghidra.feature.vt.api.main.VTScore) -> None: ...

    def setDestinationAddress(self, __a0: ghidra.program.model.address.Address) -> None: ...

    def setDestinationLength(self, __a0: int) -> None: ...

    def setSimilarityScore(self, __a0: ghidra.feature.vt.api.main.VTScore) -> None: ...

    def setSourceAddress(self, __a0: ghidra.program.model.address.Address) -> None: ...

    def setSourceLength(self, __a0: int) -> None: ...

    def setTag(self, __a0: ghidra.feature.vt.api.main.VTMatchTag) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def associationType(self) -> ghidra.feature.vt.api.main.VTAssociationType: ...

    @associationType.setter
    def associationType(self, value: ghidra.feature.vt.api.main.VTAssociationType) -> None: ...

    @property
    def confidenceScore(self) -> ghidra.feature.vt.api.main.VTScore: ...

    @confidenceScore.setter
    def confidenceScore(self, value: ghidra.feature.vt.api.main.VTScore) -> None: ...

    @property
    def destinationAddress(self) -> ghidra.program.model.address.Address: ...

    @destinationAddress.setter
    def destinationAddress(self, value: ghidra.program.model.address.Address) -> None: ...

    @property
    def destinationLength(self) -> int: ...

    @destinationLength.setter
    def destinationLength(self, value: int) -> None: ...

    @property
    def matchSet(self) -> ghidra.feature.vt.api.main.VTMatchSet: ...

    @property
    def similarityScore(self) -> ghidra.feature.vt.api.main.VTScore: ...

    @similarityScore.setter
    def similarityScore(self, value: ghidra.feature.vt.api.main.VTScore) -> None: ...

    @property
    def sourceAddress(self) -> ghidra.program.model.address.Address: ...

    @sourceAddress.setter
    def sourceAddress(self, value: ghidra.program.model.address.Address) -> None: ...

    @property
    def sourceLength(self) -> int: ...

    @sourceLength.setter
    def sourceLength(self, value: int) -> None: ...

    @property
    def tag(self) -> ghidra.feature.vt.api.main.VTMatchTag: ...

    @tag.setter
    def tag(self, value: ghidra.feature.vt.api.main.VTMatchTag) -> None: ...
