import ghidra.app.plugin.core.compositeeditor
import ghidra.framework.options
import java.lang


class EditorOptionManager(object, ghidra.framework.options.OptionsChangeListener, ghidra.app.plugin.core.compositeeditor.StructureEditorOptionManager, ghidra.app.plugin.core.compositeeditor.UnionEditorOptionManager):




    def __init__(self, __a0: ghidra.framework.plugintool.Plugin): ...



    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def optionsChanged(self, __a0: ghidra.framework.options.ToolOptions, __a1: unicode, __a2: object, __a3: object) -> None: ...

    def showStructureNumbersInHex(self) -> bool: ...

    def showUnionNumbersInHex(self) -> bool: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
