import db
import ghidra.feature.fid.db
import ghidra.feature.fid.hash
import java.lang


class RelationsTable(object):




    def __init__(self, __a0: db.DBHandle): ...



    def createInferiorRelation(self, __a0: ghidra.feature.fid.db.FunctionRecord, __a1: ghidra.feature.fid.db.FunctionRecord) -> None: ...

    def createRelation(self, __a0: ghidra.feature.fid.db.FunctionRecord, __a1: ghidra.feature.fid.db.FunctionRecord, __a2: ghidra.feature.fid.db.RelationType) -> None: ...

    @staticmethod
    def createTables(__a0: db.DBHandle) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getInferiorFullRelation(self, __a0: ghidra.feature.fid.hash.FidHashQuad, __a1: ghidra.feature.fid.db.FunctionRecord) -> bool: ...

    def getSuperiorFullRelation(self, __a0: ghidra.feature.fid.db.FunctionRecord, __a1: ghidra.feature.fid.hash.FidHashQuad) -> bool: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
