from typing import List
import ghidra.util.task
import java.lang


class MarkupItemManagerImpl(object):




    def __init__(self, __a0: ghidra.feature.vt.api.db.VTAssociationDB): ...



    def clearCache(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getMarkupItems(self, __a0: ghidra.util.task.TaskMonitor) -> List[object]: ...

    def hasAppliedMarkupItems(self) -> bool: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
