import ghidra.feature.vt.api.impl
import ghidra.framework.options
import ghidra.program.model.address
import java.lang


class ProgramCorrelatorInfoImpl(object, ghidra.feature.vt.api.impl.VTProgramCorrelatorInfo):




    def __init__(self, __a0: ghidra.feature.vt.api.db.VTMatchSetDB): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getCorrelatorClassName(self) -> unicode: ...

    def getDestinationAddressSet(self) -> ghidra.program.model.address.AddressSetView: ...

    def getName(self) -> unicode: ...

    def getOptions(self) -> ghidra.framework.options.Options: ...

    def getSourceAddressSet(self) -> ghidra.program.model.address.AddressSetView: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def correlatorClassName(self) -> unicode: ...

    @property
    def destinationAddressSet(self) -> ghidra.program.model.address.AddressSetView: ...

    @property
    def name(self) -> unicode: ...

    @property
    def options(self) -> ghidra.framework.options.Options: ...

    @property
    def sourceAddressSet(self) -> ghidra.program.model.address.AddressSetView: ...
