import ghidra.program.model.data
import java.lang


class Sequence(object):




    def __init__(self, start: long, end: long, stringDataType: ghidra.program.model.data.AbstractStringDataType, nullTerminated: bool): ...



    def equals(self, obj: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getEnd(self) -> long: ...

    def getLength(self) -> int: ...

    def getStart(self) -> long: ...

    def getStringDataType(self) -> ghidra.program.model.data.AbstractStringDataType: ...

    def hashCode(self) -> int: ...

    def isNullTerminated(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def end(self) -> long: ...

    @property
    def length(self) -> int: ...

    @property
    def nullTerminated(self) -> bool: ...

    @property
    def start(self) -> long: ...

    @property
    def stringDataType(self) -> ghidra.program.model.data.AbstractStringDataType: ...
