import java.lang
import org.osgi.framework


class GhidraBundleActivator(object, org.osgi.framework.BundleActivator):




    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def start(self, __a0: org.osgi.framework.BundleContext) -> None: ...

    def stop(self, __a0: org.osgi.framework.BundleContext) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
