from typing import List
import ghidra.program.database.bookmark
import java.lang


class BookmarkTypeDBAdapterV0(ghidra.program.database.bookmark.BookmarkTypeDBAdapter):




    def __init__(self, dbHandle: db.DBHandle, create: bool): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getTypeIds(self) -> List[int]: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def typeIds(self) -> List[int]: ...
