from typing import List
import ghidra.app.plugin.core.instructionsearch.model
import ghidra.program.model.address
import java.lang


class InstructionMetadata(object):




    def __init__(self, __a0: ghidra.app.plugin.core.instructionsearch.model.MaskContainer): ...



    def equals(self, __a0: object) -> bool: ...

    def getAddr(self) -> ghidra.program.model.address.Address: ...

    def getClass(self) -> java.lang.Class: ...

    def getMaskContainer(self) -> ghidra.app.plugin.core.instructionsearch.model.MaskContainer: ...

    def getOperands(self) -> List[object]: ...

    def getTextRep(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def isInstruction(self) -> bool: ...

    def isMasked(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setAddr(self, __a0: ghidra.program.model.address.Address) -> None: ...

    def setIsInstruction(self, __a0: bool) -> None: ...

    def setMasked(self, __a0: bool) -> None: ...

    def setOperands(self, __a0: List[object]) -> None: ...

    def setTextRep(self, __a0: unicode) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def addr(self) -> ghidra.program.model.address.Address: ...

    @addr.setter
    def addr(self, value: ghidra.program.model.address.Address) -> None: ...

    @property
    def instruction(self) -> bool: ...

    @property
    def maskContainer(self) -> ghidra.app.plugin.core.instructionsearch.model.MaskContainer: ...

    @property
    def masked(self) -> bool: ...

    @masked.setter
    def masked(self, value: bool) -> None: ...

    @property
    def operands(self) -> List[object]: ...

    @operands.setter
    def operands(self, value: List[object]) -> None: ...

    @property
    def textRep(self) -> unicode: ...

    @textRep.setter
    def textRep(self, value: unicode) -> None: ...
