import java.lang


class MaskSettings(object):




    def __init__(self, __a0: bool, __a1: bool, __a2: bool): ...



    def clear(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def isMaskAddresses(self) -> bool: ...

    def isMaskOperands(self) -> bool: ...

    def isMaskScalars(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setMaskAddresses(self, __a0: bool) -> None: ...

    def setMaskOperands(self, __a0: bool) -> None: ...

    def setMaskScalars(self, __a0: bool) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def maskAddresses(self) -> bool: ...

    @maskAddresses.setter
    def maskAddresses(self, value: bool) -> None: ...

    @property
    def maskOperands(self) -> bool: ...

    @maskOperands.setter
    def maskOperands(self, value: bool) -> None: ...

    @property
    def maskScalars(self) -> bool: ...

    @maskScalars.setter
    def maskScalars(self, value: bool) -> None: ...
