import ghidra.app.util.importer
import ghidra.util.task
import java.lang


class AndroidProjectCreator(object):
    androidDirectory: generic.jar.ResourceFile



    def __init__(self, __a0: ghidra.formats.gfilesystem.GFile, __a1: java.io.File): ...



    def create(self, __a0: ghidra.util.task.TaskMonitor) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getLog(self) -> ghidra.app.util.importer.MessageLog: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def log(self) -> ghidra.app.util.importer.MessageLog: ...
