import generic.jar
import java.lang


class SleighLanguageValidator(object):




    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @staticmethod
    def validateCspecFile(cspecFile: generic.jar.ResourceFile) -> None: ...

    @staticmethod
    def validateLdefsFile(ldefsFile: generic.jar.ResourceFile) -> None: ...

    @staticmethod
    def validatePspecFile(pspecFile: generic.jar.ResourceFile) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
