import generic.jar
import ghidra.program.model.lang
import java.lang


class SleighCompilerSpecDescription(ghidra.program.model.lang.BasicCompilerSpecDescription):




    def __init__(self, id: ghidra.program.model.lang.CompilerSpecID, name: unicode, file: generic.jar.ResourceFile): ...



    def equals(self, obj: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getCompilerSpecID(self) -> ghidra.program.model.lang.CompilerSpecID: ...

    def getCompilerSpecName(self) -> unicode: ...

    def getFile(self) -> generic.jar.ResourceFile: ...

    def getSource(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def file(self) -> generic.jar.ResourceFile: ...

    @property
    def source(self) -> unicode: ...
