import ghidra.app.analyzers
import ghidra.program.model.listing
import ghidra.xml
import java.io
import java.lang
import java.util


class FuncDBsmall(object, ghidra.app.analyzers.FuncDB):




    @overload
    def __init__(self): ...

    @overload
    def __init__(self, __a0: ghidra.program.model.listing.Program): ...



    def addLibrary(self, __a0: ghidra.app.analyzers.LibraryRecord) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getRecords(self) -> java.util.TreeSet: ...

    def hashCode(self) -> int: ...

    def mergeWith(self, __a0: ghidra.app.analyzers.FuncDBsmall) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    @overload
    def query(self, __a0: ghidra.program.model.listing.Function) -> java.util.ArrayList: ...

    @overload
    def query(self, __a0: long) -> java.util.ArrayList: ...

    def restoreXml(self, __a0: ghidra.xml.XmlPullParser) -> None: ...

    def saveXml(self, __a0: java.io.Writer) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def records(self) -> java.util.TreeSet: ...
