import ghidra.program.model.listing
import ghidra.program.model.symbol
import java.lang


class SymbolFilter(object):








    def accepts(self, __a0: ghidra.program.model.symbol.Symbol, __a1: ghidra.program.model.listing.Program) -> bool: ...

    def acceptsAll(self) -> bool: ...

    def acceptsDefaultLabelSymbols(self) -> bool: ...

    def acceptsOnlyCodeSymbols(self) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
