import java.lang
import java.util


class CompositeVertex(object):




    @overload
    def __init__(self, __a0: java.util.Collection): ...

    @overload
    def __init__(self, __a0: object): ...

    @overload
    def __init__(self, __a0: java.util.Collection, __a1: java.util.Collection): ...



    def addInternalEdge(self, __a0: object) -> None: ...

    def collectInternalEdges(self) -> java.util.Set: ...

    def collectSimpleVertices(self) -> java.util.Set: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
