import ghidra.app.util.html
import ghidra.program.model.data
import java.awt
import java.lang


class EmptyVariableTextLine(ghidra.app.util.html.VariableTextLine, ghidra.app.util.html.PlaceHolderLine):




    def __init__(self, numberOfCharacters: int): ...



    def copy(self) -> ghidra.app.util.html.ValidatableLine: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDataType(self) -> ghidra.program.model.data.DataType: ...

    def getText(self) -> unicode: ...

    def getVariableName(self) -> unicode: ...

    def getVariableNameColor(self) -> java.awt.Color: ...

    def getVariableType(self) -> unicode: ...

    def getVariableTypeColor(self) -> java.awt.Color: ...

    def hasUniversalId(self) -> bool: ...

    def hashCode(self) -> int: ...

    def isDiffColored(self) -> bool: ...

    def isValidated(self) -> bool: ...

    def matches(self, otherValidatableLine: ghidra.app.util.html.ValidatableLine) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setValidationLine(self, line: ghidra.app.util.html.ValidatableLine) -> None: ...

    def toString(self) -> unicode: ...

    def updateColor(self, otherValidatableLine: ghidra.app.util.html.ValidatableLine, invalidColor: java.awt.Color) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def validated(self) -> bool: ...
