import ghidra.app.util.importer
import ghidra.framework.options
import ghidra.program.model.listing
import ghidra.util.task
import java.lang


class AnalysisScheduler(object):








    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getName(self) -> unicode: ...

    def getPriority(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def optionsChanged(self, __a0: ghidra.framework.options.Options) -> None: ...

    def registerOptions(self, __a0: ghidra.framework.options.Options) -> None: ...

    def runAnalyzer(self, __a0: ghidra.program.model.listing.Program, __a1: ghidra.util.task.TaskMonitor, __a2: ghidra.app.util.importer.MessageLog) -> bool: ...

    def runCanceled(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def name(self) -> unicode: ...

    @property
    def priority(self) -> int: ...
