import ghidra.program.model.address
import java.lang


class ReferenceAddressPair(object):




    def __init__(self, source: ghidra.program.model.address.Address, destination: ghidra.program.model.address.Address): ...



    def equals(self, obj: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDestination(self) -> ghidra.program.model.address.Address: ...

    def getSource(self) -> ghidra.program.model.address.Address: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def destination(self) -> ghidra.program.model.address.Address: ...

    @property
    def source(self) -> ghidra.program.model.address.Address: ...
