import ghidra.graph
import java.lang


class DefaultGEdge(object, ghidra.graph.GEdge):




    def __init__(self, __a0: object, __a1: object): ...



    def equals(self, obj: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getEnd(self) -> V: ...

    def getStart(self) -> V: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def end(self) -> object: ...

    @property
    def start(self) -> object: ...
