import ghidra.pcodeCPort.address
import ghidra.pcodeCPort.space
import ghidra.pcodeCPort.translate
import java.lang
import org.jdom


class Range(object, java.lang.Comparable):




    @overload
    def __init__(self): ...

    @overload
    def __init__(self, __a0: ghidra.pcodeCPort.space.AddrSpace, __a1: long, __a2: long): ...



    @overload
    def compareTo(self, __a0: ghidra.pcodeCPort.address.Range) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getFirst(self) -> long: ...

    def getFirstAddr(self) -> ghidra.pcodeCPort.address.Address: ...

    def getLast(self) -> long: ...

    def getLastAddr(self) -> ghidra.pcodeCPort.address.Address: ...

    def getLastAddrOpen(self, __a0: ghidra.pcodeCPort.translate.Translate) -> ghidra.pcodeCPort.address.Address: ...

    def getSpace(self) -> ghidra.pcodeCPort.space.AddrSpace: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def restoreXml(self, __a0: org.jdom.Element, __a1: ghidra.pcodeCPort.translate.Translate) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def first(self) -> long: ...

    @property
    def firstAddr(self) -> ghidra.pcodeCPort.address.Address: ...

    @property
    def last(self) -> long: ...

    @property
    def lastAddr(self) -> ghidra.pcodeCPort.address.Address: ...

    @property
    def space(self) -> ghidra.pcodeCPort.space.AddrSpace: ...
