import ghidra.app.util.demangler
import ghidra.program.model.listing
import java.lang


class GnuDemangler(object, ghidra.app.util.demangler.Demangler):




    def __init__(self): ...



    def canDemangle(self, __a0: ghidra.program.model.listing.Program) -> bool: ...

    def createDefaultOptions(self) -> ghidra.app.util.demangler.DemanglerOptions: ...

    @overload
    def demangle(self, __a0: unicode) -> ghidra.app.util.demangler.DemangledObject: ...

    @overload
    def demangle(self, __a0: unicode, __a1: bool) -> ghidra.app.util.demangler.DemangledObject: ...

    @overload
    def demangle(self, __a0: unicode, __a1: ghidra.app.util.demangler.DemanglerOptions) -> ghidra.app.util.demangler.DemangledObject: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
