import ghidra.app.decompiler.component
import ghidra.program.model.address
import ghidra.program.model.listing
import ghidra.program.util
import ghidra.util.bean.field
import java.lang
import utility.function


class DecompilerCallbackHandler(object):








    def annotationClicked(self, annotation: ghidra.util.bean.field.AnnotatedTextFieldElement, newWindow: bool) -> None: ...

    def contextChanged(self) -> None: ...

    def decompileDataChanged(self, decompileData: ghidra.app.decompiler.component.DecompileData) -> None: ...

    def doWheNotBusy(self, c: utility.function.Callback) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def exportLocation(self) -> None: ...

    def getClass(self) -> java.lang.Class: ...

    def goToAddress(self, addr: ghidra.program.model.address.Address, newWindow: bool) -> None: ...

    def goToFunction(self, function: ghidra.program.model.listing.Function, newWindow: bool) -> None: ...

    def goToLabel(self, labelName: unicode, newWindow: bool) -> None: ...

    def goToScalar(self, value: long, newWindow: bool) -> None: ...

    def hashCode(self) -> int: ...

    def locationChanged(self, programLocation: ghidra.program.util.ProgramLocation) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def selectionChanged(self, programSelection: ghidra.program.util.ProgramSelection) -> None: ...

    def setStatusMessage(self, message: unicode) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def statusMessage(self) -> None: ...  # No getter available.

    @statusMessage.setter
    def statusMessage(self, value: unicode) -> None: ...
