from typing import List
import docking.widgets.table
import ghidra.feature.vt.api.main
import java.lang
import java.util
import javax.swing.event
import javax.swing.table


class VTProgramTableCorrelatorModel(docking.widgets.table.AbstractGTableModel):




    def __init__(self, __a0: ghidra.feature.vt.gui.wizard.CorrelatorPanel, __a1: java.util.Set): ...



    def addTableModelListener(self, __a0: javax.swing.event.TableModelListener) -> None: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def findColumn(self, __a0: unicode) -> int: ...

    def fireTableCellUpdated(self, __a0: int, __a1: int) -> None: ...

    def fireTableChanged(self, __a0: javax.swing.event.TableModelEvent) -> None: ...

    def fireTableDataChanged(self) -> None: ...

    def fireTableRowsDeleted(self, __a0: int, __a1: int) -> None: ...

    def fireTableRowsInserted(self, __a0: int, __a1: int) -> None: ...

    def fireTableRowsUpdated(self, __a0: int, __a1: int) -> None: ...

    def fireTableStructureChanged(self) -> None: ...

    def getClass(self) -> java.lang.Class: ...

    def getColumnClass(self, __a0: int) -> java.lang.Class: ...

    def getColumnCount(self) -> int: ...

    def getColumnName(self, __a0: int) -> unicode: ...

    @overload
    def getColumnValueForRow(self, __a0: ghidra.feature.vt.api.main.VTProgramCorrelatorFactory, __a1: int) -> object: ...

    @overload
    def getColumnValueForRow(self, __a0: object, __a1: int) -> object: ...

    def getLastSelectedObjects(self) -> List[object]: ...

    def getListeners(self, __a0: java.lang.Class) -> List[java.util.EventListener]: ...

    def getModelData(self) -> List[object]: ...

    def getName(self) -> unicode: ...

    def getPreferredColumnWidth(self, __a0: int) -> int: ...

    def getRowCount(self) -> int: ...

    def getRowIndex(self, __a0: object) -> int: ...

    def getRowObject(self, __a0: int) -> object: ...

    def getSelectedFactories(self) -> List[object]: ...

    def getTableModelListeners(self) -> List[javax.swing.event.TableModelListener]: ...

    def getValueAt(self, __a0: int, __a1: int) -> object: ...

    def hashCode(self) -> int: ...

    def isCellEditable(self, __a0: int, __a1: int) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def refresh(self) -> None: ...

    def removeTableModelListener(self, __a0: javax.swing.event.TableModelListener) -> None: ...

    def setLastSelectedObjects(self, __a0: List[object]) -> None: ...

    def setValueAt(self, __a0: object, __a1: int, __a2: int) -> None: ...

    def toString(self) -> unicode: ...

    @staticmethod
    def unwrap(__a0: javax.swing.table.TableModel) -> javax.swing.table.TableModel: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def columnCount(self) -> int: ...

    @property
    def modelData(self) -> List[object]: ...

    @property
    def name(self) -> unicode: ...

    @property
    def selectedFactories(self) -> List[object]: ...
