import ghidra.app.plugin.core.functiongraph.graph.vertex
import ghidra.app.plugin.core.functiongraph.mvc
import ghidra.app.plugin.core.functiongraph.util.job
import ghidra.graph.job
import ghidra.graph.viewer.layout
import ghidra.util.task
import java.awt.geom
import java.lang
import java.util


class GroupVertexFunctionGraphJob(ghidra.app.plugin.core.functiongraph.util.job.AbstractGroupingFunctionGraphJob):








    def calculateDefaultLayoutLocations(self, __a0: java.util.Set) -> ghidra.graph.viewer.layout.LayoutPositions: ...

    def canShortcut(self) -> bool: ...

    @staticmethod
    def createNewGroupJob(__a0: ghidra.app.plugin.core.functiongraph.mvc.FGController, __a1: ghidra.app.plugin.core.functiongraph.graph.vertex.GroupedFunctionGraphVertex, __a2: java.awt.geom.Point2D, __a3: bool, __a4: bool) -> ghidra.app.plugin.core.functiongraph.util.job.GroupVertexFunctionGraphJob: ...

    @staticmethod
    def createRegroupJob(__a0: ghidra.app.plugin.core.functiongraph.mvc.FGController, __a1: ghidra.app.plugin.core.functiongraph.graph.vertex.GroupedFunctionGraphVertex, __a2: java.awt.geom.Point2D, __a3: bool, __a4: bool) -> ghidra.app.plugin.core.functiongraph.util.job.GroupVertexFunctionGraphJob: ...

    @staticmethod
    def createUpdateGroupJob(__a0: ghidra.app.plugin.core.functiongraph.mvc.FGController, __a1: ghidra.app.plugin.core.functiongraph.graph.vertex.GroupedFunctionGraphVertex, __a2: java.util.Set, __a3: bool) -> ghidra.app.plugin.core.functiongraph.util.job.GroupVertexFunctionGraphJob: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def execute(self, __a0: ghidra.graph.job.GraphJobListener) -> None: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def isFinished(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setBusyListener(self, __a0: ghidra.util.task.BusyListener) -> None: ...

    def setPercentComplete(self, __a0: float) -> None: ...

    def shortcut(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
