from typing import List
import ghidra.pcodeCPort.address
import ghidra.pcodeCPort.globalcontext
import java.lang


class ContextCache(object):




    def __init__(self, __a0: ghidra.pcodeCPort.globalcontext.ContextDatabase): ...



    def allowSet(self, __a0: bool) -> None: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getContext(self, __a0: ghidra.pcodeCPort.address.Address, __a1: List[int]) -> None: ...

    def getDatabase(self) -> ghidra.pcodeCPort.globalcontext.ContextDatabase: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setContext(self, __a0: ghidra.pcodeCPort.address.Address, __a1: int, __a2: int, __a3: int) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def database(self) -> ghidra.pcodeCPort.globalcontext.ContextDatabase: ...
