import java.lang
import javax.swing


class NavigatableIconFactory(object):




    def __init__(self): ...



    @staticmethod
    def createSnapshotOverlayIcon(primaryIcon: javax.swing.Icon) -> javax.swing.ImageIcon: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
