import ghidra.program.model.address
import ghidra.program.model.listing
import java.lang


class ProgramCoordinator(object):




    def __init__(self, programManager: ghidra.app.services.ProgramManager, languageService: ghidra.program.model.lang.LanguageService): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getProgram(self, path: unicode, address: ghidra.program.model.address.Address) -> ghidra.program.model.listing.Program: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
