import java.lang


class QueryData(object):




    @overload
    def __init__(self, queryString: unicode, caseSensitive: bool): ...

    @overload
    def __init__(self, queryString: unicode, caseSensitive: bool, includeDynamicLables: bool): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getQueryString(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def isCaseSensitive(self) -> bool: ...

    def isIncludeDynamicLables(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def caseSensitive(self) -> bool: ...

    @property
    def includeDynamicLables(self) -> bool: ...

    @property
    def queryString(self) -> unicode: ...
