import ghidra.graph.visualization.mouse
import java.awt
import java.awt.event
import java.lang
import org.jungrapht.visualization


class JgtTranslatingPlugin(ghidra.graph.visualization.mouse.AbstractJgtGraphMousePlugin):




    @overload
    def __init__(self): ...

    @overload
    def __init__(self, __a0: int): ...



    def checkModifiers(self, __a0: java.awt.event.MouseEvent) -> bool: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getCursor(self) -> java.awt.Cursor: ...

    def getGraphViewer(self, __a0: java.awt.event.MouseEvent) -> org.jungrapht.visualization.VisualizationViewer: ...

    def getModifiersEx(self) -> int: ...

    def getSatelliteGraphViewer(self, __a0: java.awt.event.MouseEvent) -> org.jungrapht.visualization.SatelliteVisualizationViewer: ...

    def getViewer(self, __a0: java.awt.event.MouseEvent) -> org.jungrapht.visualization.VisualizationViewer: ...

    def hashCode(self) -> int: ...

    def installCursor(self, __a0: java.awt.Cursor, __a1: java.awt.event.MouseEvent) -> None: ...

    def mouseClicked(self, __a0: java.awt.event.MouseEvent) -> None: ...

    def mouseDragged(self, __a0: java.awt.event.MouseEvent) -> None: ...

    def mouseEntered(self, __a0: java.awt.event.MouseEvent) -> None: ...

    def mouseExited(self, __a0: java.awt.event.MouseEvent) -> None: ...

    def mouseMoved(self, __a0: java.awt.event.MouseEvent) -> None: ...

    def mousePressed(self, __a0: java.awt.event.MouseEvent) -> None: ...

    def mouseReleased(self, __a0: java.awt.event.MouseEvent) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setCursor(self, __a0: java.awt.Cursor) -> None: ...

    def setModifiers(self, __a0: int) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
