import ghidra.pcodeCPort.sleigh
import java.lang


class ByteBufferPtr(object):




    def __init__(self, __a0: List[int], __a1: int): ...



    def add(self, __a0: int) -> ghidra.pcodeCPort.sleigh.ByteBufferPtr: ...

    def equals(self, __a0: object) -> bool: ...

    def get(self, __a0: int) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
