import ghidra.util.classfinder
import java.lang


class ClassExclusionFilter(object, ghidra.util.classfinder.ClassFilter):




    def __init__(self, __a0: List[java.lang.Class]): ...



    def accepts(self, c: java.lang.Class) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
