import ghidra.feature.vt.api.main
import ghidra.program.model.address
import ghidra.program.model.symbol
import ghidra.program.util
import java.lang


class VTImpliedMatchInfo(ghidra.feature.vt.api.main.VTMatchInfo):




    def __init__(self, __a0: ghidra.feature.vt.api.main.VTMatchSet, __a1: ghidra.program.model.symbol.Reference, __a2: ghidra.program.model.symbol.Reference): ...



    def equals(self, __a0: object) -> bool: ...

    def getAssociationType(self) -> ghidra.feature.vt.api.main.VTAssociationType: ...

    def getClass(self) -> java.lang.Class: ...

    def getConfidenceScore(self) -> ghidra.feature.vt.api.main.VTScore: ...

    def getDestinationAddress(self) -> ghidra.program.model.address.Address: ...

    def getDestinationLength(self) -> int: ...

    def getDestinationReference(self) -> ghidra.program.model.symbol.Reference: ...

    def getDestinationReferenceAddress(self) -> ghidra.program.model.address.Address: ...

    def getDestinationReferenceLocation(self) -> ghidra.program.util.ProgramLocation: ...

    def getMatchSet(self) -> ghidra.feature.vt.api.main.VTMatchSet: ...

    def getSimilarityScore(self) -> ghidra.feature.vt.api.main.VTScore: ...

    def getSourceAddress(self) -> ghidra.program.model.address.Address: ...

    def getSourceLength(self) -> int: ...

    def getSourceReference(self) -> ghidra.program.model.symbol.Reference: ...

    def getSourceReferenceAddress(self) -> ghidra.program.model.address.Address: ...

    def getSourceReferenceLocation(self) -> ghidra.program.util.ProgramLocation: ...

    def getTag(self) -> ghidra.feature.vt.api.main.VTMatchTag: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setAssociationType(self, __a0: ghidra.feature.vt.api.main.VTAssociationType) -> None: ...

    def setConfidenceScore(self, __a0: ghidra.feature.vt.api.main.VTScore) -> None: ...

    def setDestinationAddress(self, __a0: ghidra.program.model.address.Address) -> None: ...

    def setDestinationLength(self, __a0: int) -> None: ...

    def setSimilarityScore(self, __a0: ghidra.feature.vt.api.main.VTScore) -> None: ...

    def setSourceAddress(self, __a0: ghidra.program.model.address.Address) -> None: ...

    def setSourceLength(self, __a0: int) -> None: ...

    def setTag(self, __a0: ghidra.feature.vt.api.main.VTMatchTag) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def destinationReference(self) -> ghidra.program.model.symbol.Reference: ...

    @property
    def destinationReferenceAddress(self) -> ghidra.program.model.address.Address: ...

    @property
    def destinationReferenceLocation(self) -> ghidra.program.util.ProgramLocation: ...

    @property
    def sourceReference(self) -> ghidra.program.model.symbol.Reference: ...

    @property
    def sourceReferenceAddress(self) -> ghidra.program.model.address.Address: ...

    @property
    def sourceReferenceLocation(self) -> ghidra.program.util.ProgramLocation: ...
