import ghidra.app.plugin.core.functionwindow
import ghidra.program.model.listing
import java.lang


class FunctionRowObject(object, java.lang.Comparable):




    def __init__(self, __a0: ghidra.program.model.listing.Function): ...



    @overload
    def compareTo(self, __a0: ghidra.app.plugin.core.functionwindow.FunctionRowObject) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getFunction(self) -> ghidra.program.model.listing.Function: ...

    def getKey(self) -> long: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def function(self) -> ghidra.program.model.listing.Function: ...

    @property
    def key(self) -> long: ...
