import db
import ghidra.feature.vt.api.db
import java.lang


class VTAssociationTableDBAdapterV0(ghidra.feature.vt.api.db.VTAssociationTableDBAdapter):




    @overload
    def __init__(self, __a0: db.DBHandle): ...

    @overload
    def __init__(self, __a0: db.DBHandle, __a1: db.OpenMode, __a2: ghidra.util.task.TaskMonitor): ...



    @staticmethod
    def createAdapter(__a0: db.DBHandle) -> ghidra.feature.vt.api.db.VTAssociationTableDBAdapter: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getRecords(self) -> db.RecordIterator: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def records(self) -> db.RecordIterator: ...
