from typing import List
import db
import ghidra.feature.vt.api.db
import ghidra.feature.vt.api.main
import ghidra.program.database.map
import ghidra.program.model.address
import java.lang


class VTMatchSetTableDBAdapter(object):





    class ColumnDescription(java.lang.Enum):
        CORRELATOR_CLASS_COL: ghidra.feature.vt.api.db.VTMatchSetTableDBAdapter.ColumnDescription = CORRELATOR_CLASS_COL
        CORRELATOR_NAME_COL: ghidra.feature.vt.api.db.VTMatchSetTableDBAdapter.ColumnDescription = CORRELATOR_NAME_COL
        OPTIONS_COL: ghidra.feature.vt.api.db.VTMatchSetTableDBAdapter.ColumnDescription = OPTIONS_COL







        def column(self) -> int: ...

        @overload
        def compareTo(self, __a0: java.lang.Enum) -> int: ...

        @overload
        def compareTo(self, __a0: object) -> int: ...

        def equals(self, __a0: object) -> bool: ...

        def getClass(self) -> java.lang.Class: ...

        def getColumnClass(self) -> java.lang.Class: ...

        def getDeclaringClass(self) -> java.lang.Class: ...

        def hashCode(self) -> int: ...

        def name(self) -> unicode: ...

        def notify(self) -> None: ...

        def notifyAll(self) -> None: ...

        def ordinal(self) -> int: ...

        def toString(self) -> unicode: ...

        @overload
        @staticmethod
        def valueOf(__a0: unicode) -> ghidra.feature.vt.api.db.VTMatchSetTableDBAdapter.ColumnDescription: ...

        @overload
        @staticmethod
        def valueOf(__a0: java.lang.Class, __a1: unicode) -> java.lang.Enum: ...

        @staticmethod
        def values() -> List[ghidra.feature.vt.api.db.VTMatchSetTableDBAdapter.ColumnDescription]: ...

        @overload
        def wait(self) -> None: ...

        @overload
        def wait(self, __a0: long) -> None: ...

        @overload
        def wait(self, __a0: long, __a1: int) -> None: ...

        @property
        def columnClass(self) -> java.lang.Class: ...

    def __init__(self): ...



    def createMatchSetRecord(self, __a0: long, __a1: ghidra.feature.vt.api.main.VTProgramCorrelator) -> db.Record: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDestinationAddressSet(self, __a0: db.Record, __a1: ghidra.program.database.map.AddressMap) -> ghidra.program.model.address.AddressSet: ...

    def getNextMatchSetID(self) -> long: ...

    def getRecord(self, __a0: long) -> db.Record: ...

    def getRecords(self) -> db.RecordIterator: ...

    def getSourceAddressSet(self, __a0: db.Record, __a1: ghidra.program.database.map.AddressMap) -> ghidra.program.model.address.AddressSet: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def nextMatchSetID(self) -> long: ...

    @property
    def records(self) -> db.RecordIterator: ...
