import db
import ghidra.feature.vt.api.main
import ghidra.program.database
import ghidra.program.model.address
import ghidra.util
import java.lang


class VTMatchDB(ghidra.program.database.DatabaseObject, ghidra.feature.vt.api.main.VTMatch):




    def __init__(self, __a0: ghidra.program.database.DBObjectCache, __a1: db.Record, __a2: ghidra.feature.vt.api.db.VTMatchSetDB): ...



    def checkDeleted(self) -> None: ...

    @overload
    def checkIsValid(self) -> bool: ...

    @overload
    def checkIsValid(self, __a0: db.Record) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getAssociation(self) -> ghidra.feature.vt.api.main.VTAssociation: ...

    def getClass(self) -> java.lang.Class: ...

    def getConfidenceScore(self) -> ghidra.feature.vt.api.main.VTScore: ...

    def getDestinationAddress(self) -> ghidra.program.model.address.Address: ...

    def getDestinationLength(self) -> int: ...

    def getKey(self) -> long: ...

    def getLengthType(self) -> unicode: ...

    def getMatchSet(self) -> ghidra.feature.vt.api.main.VTMatchSet: ...

    def getSimilarityScore(self) -> ghidra.feature.vt.api.main.VTScore: ...

    def getSourceAddress(self) -> ghidra.program.model.address.Address: ...

    def getSourceLength(self) -> int: ...

    def getTag(self) -> ghidra.feature.vt.api.main.VTMatchTag: ...

    def hashCode(self) -> int: ...

    def isDeleted(self) -> bool: ...

    def isInvalid(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setInvalid(self) -> None: ...

    def setTag(self, __a0: ghidra.feature.vt.api.main.VTMatchTag) -> None: ...

    def toString(self) -> unicode: ...

    def validate(self, __a0: ghidra.util.Lock) -> bool: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def association(self) -> ghidra.feature.vt.api.main.VTAssociation: ...

    @property
    def confidenceScore(self) -> ghidra.feature.vt.api.main.VTScore: ...

    @property
    def destinationAddress(self) -> ghidra.program.model.address.Address: ...

    @property
    def destinationLength(self) -> int: ...

    @property
    def lengthType(self) -> unicode: ...

    @property
    def matchSet(self) -> ghidra.feature.vt.api.main.VTMatchSet: ...

    @property
    def similarityScore(self) -> ghidra.feature.vt.api.main.VTScore: ...

    @property
    def sourceAddress(self) -> ghidra.program.model.address.Address: ...

    @property
    def sourceLength(self) -> int: ...

    @property
    def tag(self) -> ghidra.feature.vt.api.main.VTMatchTag: ...

    @tag.setter
    def tag(self, value: ghidra.feature.vt.api.main.VTMatchTag) -> None: ...
