import ghidra.javaclass.format.attributes
import ghidra.program.model.data
import java.lang


class ModuleAttribute(ghidra.javaclass.format.attributes.AbstractAttributeInfo):








    def equals(self, __a0: object) -> bool: ...

    def getAttributeLength(self) -> int: ...

    def getAttributeNameIndex(self) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def getExportsCount(self) -> int: ...

    def getModuleFlags(self) -> int: ...

    def getModuleNameIndex(self) -> int: ...

    def getModuleVersionIndex(self) -> int: ...

    def getOffset(self) -> long: ...

    def getOpensCount(self) -> int: ...

    def getProvidesCount(self) -> int: ...

    def getRequiresCount(self) -> int: ...

    def getUsesCount(self) -> int: ...

    def getUsesEntry(self, __a0: int) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def exportsCount(self) -> int: ...

    @property
    def moduleFlags(self) -> int: ...

    @property
    def moduleNameIndex(self) -> int: ...

    @property
    def moduleVersionIndex(self) -> int: ...

    @property
    def opensCount(self) -> int: ...

    @property
    def providesCount(self) -> int: ...

    @property
    def requiresCount(self) -> int: ...

    @property
    def usesCount(self) -> int: ...
