from typing import Iterator
import java.lang
import java.util
import java.util.function


class DirectoryVisitor(object, java.lang.Iterable):




    @overload
    def __init__(self, __a0: java.io.File, __a1: java.io.FileFilter): ...

    @overload
    def __init__(self, __a0: java.util.Collection, __a1: java.io.FileFilter): ...

    @overload
    def __init__(self, __a0: java.io.File, __a1: java.io.FileFilter, __a2: bool): ...

    @overload
    def __init__(self, __a0: java.util.Collection, __a1: java.io.FileFilter, __a2: bool): ...

    @overload
    def __init__(self, __a0: java.io.File, __a1: java.io.FileFilter, __a2: java.io.FileFilter): ...

    @overload
    def __init__(self, __a0: java.util.Collection, __a1: java.io.FileFilter, __a2: java.io.FileFilter): ...

    @overload
    def __init__(self, __a0: java.io.File, __a1: java.io.FileFilter, __a2: java.io.FileFilter, __a3: bool): ...

    @overload
    def __init__(self, __a0: java.util.Collection, __a1: java.io.FileFilter, __a2: java.io.FileFilter, __a3: bool): ...

    def __iter__(self): ...

    def equals(self, __a0: object) -> bool: ...

    def forEach(self, __a0: java.util.function.Consumer) -> None: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def iterator(self) -> java.util.Iterator: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def spliterator(self) -> java.util.Spliterator: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
