import generic.stl
import java.lang


class PreprocessorDefinitions(object):








    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def lookup(self, __a0: unicode) -> generic.stl.Pair: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def set(self, __a0: unicode, __a1: unicode) -> None: ...

    def toString(self) -> unicode: ...

    def undefine(self, __a0: unicode) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
