import ghidra.pcodeCPort.semantics
import java.lang


class StarQuality(object):
    location: ghidra.sleigh.grammar.Location



    def __init__(self, __a0: ghidra.sleigh.grammar.Location): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getId(self) -> ghidra.pcodeCPort.semantics.ConstTpl: ...

    def getSize(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setId(self, __a0: ghidra.pcodeCPort.semantics.ConstTpl) -> None: ...

    def setSize(self, __a0: int) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def id(self) -> ghidra.pcodeCPort.semantics.ConstTpl: ...

    @id.setter
    def id(self, value: ghidra.pcodeCPort.semantics.ConstTpl) -> None: ...

    @property
    def size(self) -> int: ...

    @size.setter
    def size(self, value: int) -> None: ...
