import java.lang
import java.net


class EclipseConnection(object):




    @overload
    def __init__(self): ...

    @overload
    def __init__(self, __a0: java.lang.Process, __a1: java.net.Socket): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getProcess(self) -> java.lang.Process: ...

    def getSocket(self) -> java.net.Socket: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def process(self) -> java.lang.Process: ...

    @property
    def socket(self) -> java.net.Socket: ...
