import ghidra.app.plugin.core.functiongraph.graph
import ghidra.app.plugin.core.functiongraph.graph.layout
import ghidra.framework.options
import ghidra.graph
import ghidra.graph.viewer.layout
import ghidra.util.task
import java.lang
import javax.swing


class ExperimentalLayoutProvider(ghidra.app.plugin.core.functiongraph.graph.layout.FGLayoutProvider):




    def __init__(self): ...



    def createLayoutOptions(self, __a0: ghidra.framework.options.Options) -> ghidra.app.plugin.core.functiongraph.graph.layout.FGLayoutOptions: ...

    def equals(self, __a0: object) -> bool: ...

    def getActionIcon(self) -> javax.swing.Icon: ...

    def getClass(self) -> java.lang.Class: ...

    def getFGLayout(self, __a0: ghidra.app.plugin.core.functiongraph.graph.FunctionGraph, __a1: ghidra.util.task.TaskMonitor) -> ghidra.app.plugin.core.functiongraph.graph.layout.FGLayout: ...

    @overload
    def getLayout(self, __a0: ghidra.app.plugin.core.functiongraph.graph.FunctionGraph, __a1: ghidra.util.task.TaskMonitor) -> ghidra.app.plugin.core.functiongraph.graph.layout.FGLayout: ...

    @overload
    def getLayout(self, __a0: ghidra.graph.VisualGraph, __a1: ghidra.util.task.TaskMonitor) -> ghidra.graph.viewer.layout.VisualGraphLayout: ...

    def getLayoutName(self) -> unicode: ...

    def getPriorityLevel(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def actionIcon(self) -> javax.swing.Icon: ...

    @property
    def priorityLevel(self) -> int: ...
