from typing import List
import ghidra.program.model.address
import java.lang


class ProgramLoadImage(object):




    def __init__(self, program: ghidra.program.model.listing.Program, faultHandler: ghidra.pcode.memstate.MemoryFaultHandler): ...



    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getInitializedAddressSet(self) -> ghidra.program.model.address.AddressSetView: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def read(self, bytes: List[int], size: int, addr: ghidra.program.model.address.Address, offset: int, generateInitializedMask: bool) -> List[int]: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def write(self, bytes: List[int], size: int, addr: ghidra.program.model.address.Address, offset: int) -> None: ...

    @property
    def initializedAddressSet(self) -> ghidra.program.model.address.AddressSetView: ...
