import java.awt
import java.lang


class ScreenElement(object):








    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getColor(self) -> java.awt.Color: ...

    def getColorOptionName(self) -> unicode: ...

    def getDefaultColor(self) -> java.awt.Color: ...

    def getName(self) -> unicode: ...

    def getStyle(self) -> int: ...

    def getStyleOptionName(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setColor(self, color: java.awt.Color) -> None: ...

    def setStyle(self, style: int) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def color(self) -> java.awt.Color: ...

    @color.setter
    def color(self, value: java.awt.Color) -> None: ...

    @property
    def colorOptionName(self) -> unicode: ...

    @property
    def defaultColor(self) -> java.awt.Color: ...

    @property
    def name(self) -> unicode: ...

    @property
    def style(self) -> int: ...

    @style.setter
    def style(self, value: int) -> None: ...

    @property
    def styleOptionName(self) -> unicode: ...
