from typing import List
import ghidra.file.formats.ios.img3
import ghidra.program.model.data
import java.io
import java.lang


class DataTag(ghidra.file.formats.ios.img3.AbstractImg3Tag):








    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getData(self) -> List[int]: ...

    def getDataAsInputStream(self) -> java.io.InputStream: ...

    def getDataLength(self) -> int: ...

    def getDecryptedInputStream(self, __a0: unicode, __a1: unicode) -> java.io.InputStream: ...

    def getLengthWithPadding(self) -> long: ...

    def getMagic(self) -> unicode: ...

    def getTotalLength(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def data(self) -> List[int]: ...

    @property
    def dataAsInputStream(self) -> java.io.InputStream: ...

    @property
    def lengthWithPadding(self) -> long: ...
