import ghidra.app.plugin.core.functiongraph.graph
import ghidra.app.plugin.core.functiongraph.graph.vertex
import ghidra.app.plugin.core.functiongraph.mvc
import ghidra.program.model.address
import java.awt
import java.lang
import java.util
import org.jdom


class FunctionGraphVertexAttributes(object):
    COLOR_PROPERTY_NAME: unicode = u'VERTEX_COLOR'
    GROUP_SETTINGS_PROPERTY_NAME: unicode = u'VERTEX_GROUP_SETTINGS'
    LOCATION_PROPERTY_NAME: unicode = u'VERTEX_LOCATION'
    REGROUP_SETTINGS_PROPERTY_NAME: unicode = u'VERTEX_REGROUP_SETTINGS'



    def __init__(self, __a0: ghidra.program.model.listing.Program): ...



    def clearAllPropertiesForAddresses(self, __a0: ghidra.program.model.address.AddressSetView) -> None: ...

    def clearGroupSettings(self, __a0: ghidra.app.plugin.core.functiongraph.graph.FunctionGraph) -> None: ...

    def clearGroupedVertexSettings(self, __a0: ghidra.program.model.address.Address) -> None: ...

    def clearPropertyForAddresses(self, __a0: unicode, __a1: ghidra.program.model.address.AddressSetView) -> None: ...

    def clearRegroupSettings(self, __a0: ghidra.app.plugin.core.functiongraph.graph.FunctionGraph) -> None: ...

    def clearRegroupVertexSettign(self, __a0: ghidra.program.model.address.Address) -> None: ...

    def clearVertexColor(self, __a0: ghidra.program.model.address.Address) -> None: ...

    def clearVertexLocation(self, __a0: ghidra.app.plugin.core.functiongraph.graph.vertex.FGVertex) -> None: ...

    def clearVertexLocations(self, __a0: ghidra.app.plugin.core.functiongraph.graph.FunctionGraph) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getGroupedVertexSettings(self, __a0: ghidra.app.plugin.core.functiongraph.graph.FunctionGraph) -> org.jdom.Element: ...

    def getRegroupVertexSettings(self, __a0: ghidra.app.plugin.core.functiongraph.graph.FunctionGraph) -> org.jdom.Element: ...

    def getVertexColor(self, __a0: ghidra.program.model.address.Address) -> java.awt.Color: ...

    def getVertexColors(self, __a0: ghidra.app.plugin.core.functiongraph.graph.FunctionGraph) -> java.util.Map: ...

    def getVertexLocations(self, __a0: ghidra.app.plugin.core.functiongraph.graph.FunctionGraph) -> java.util.Map: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def putGroupedVertexSettings(self, __a0: ghidra.app.plugin.core.functiongraph.graph.FunctionGraph, __a1: ghidra.app.plugin.core.functiongraph.mvc.SaveableXML) -> None: ...

    def putRegroupSettings(self, __a0: ghidra.app.plugin.core.functiongraph.graph.FunctionGraph, __a1: ghidra.app.plugin.core.functiongraph.mvc.SaveableXML) -> None: ...

    def putVertexColor(self, __a0: ghidra.program.model.address.Address, __a1: java.awt.Color) -> None: ...

    def putVertexLocation(self, __a0: ghidra.app.plugin.core.functiongraph.graph.vertex.FGVertex, __a1: java.awt.Point) -> None: ...

    def save(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
