import ghidra.app.plugin.core.functiongraph.mvc
import ghidra.graph.viewer
import ghidra.program.util
import java.lang


class NoFunctionGraphViewSettings(ghidra.app.plugin.core.functiongraph.mvc.FunctionGraphViewSettings):








    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getFunctionGraphPerspectiveInfo(self) -> ghidra.graph.viewer.GraphPerspectiveInfo: ...

    def getHighlight(self) -> ghidra.program.util.ProgramSelection: ...

    def getLocation(self) -> ghidra.program.util.ProgramLocation: ...

    def getSelection(self) -> ghidra.program.util.ProgramSelection: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setFunctionGraphPerspectiveInfo(self, __a0: ghidra.graph.viewer.GraphPerspectiveInfo) -> None: ...

    def setHighlight(self, __a0: ghidra.program.util.ProgramSelection) -> None: ...

    def setLocation(self, __a0: ghidra.program.util.ProgramLocation) -> None: ...

    def setSelection(self, __a0: ghidra.program.util.ProgramSelection) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def functionGraphPerspectiveInfo(self) -> ghidra.graph.viewer.GraphPerspectiveInfo: ...

    @functionGraphPerspectiveInfo.setter
    def functionGraphPerspectiveInfo(self, value: ghidra.graph.viewer.GraphPerspectiveInfo) -> None: ...

    @property
    def highlight(self) -> ghidra.program.util.ProgramSelection: ...

    @highlight.setter
    def highlight(self, value: ghidra.program.util.ProgramSelection) -> None: ...

    @property
    def location(self) -> ghidra.program.util.ProgramLocation: ...

    @location.setter
    def location(self, value: ghidra.program.util.ProgramLocation) -> None: ...

    @property
    def selection(self) -> ghidra.program.util.ProgramSelection: ...

    @selection.setter
    def selection(self, value: ghidra.program.util.ProgramSelection) -> None: ...
