from typing import List
import ghidra.program.model.lang
import ghidra.program.model.listing
import ghidra.xml
import java.lang


class PcodeInjectLibraryDex(ghidra.program.model.lang.PcodeInjectLibrary):




    def __init__(self, __a0: ghidra.app.plugin.processors.sleigh.SleighLanguage): ...



    def buildInjectContext(self) -> ghidra.program.model.lang.InjectContext: ...

    def equals(self, __a0: object) -> bool: ...

    def getCallFixupNames(self) -> List[unicode]: ...

    def getClass(self) -> java.lang.Class: ...

    def getConstantPool(self, __a0: ghidra.program.model.listing.Program) -> ghidra.program.model.lang.ConstantPool: ...

    def getPayload(self, __a0: int, __a1: unicode, __a2: ghidra.program.model.listing.Program, __a3: unicode) -> ghidra.program.model.lang.InjectPayload: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def restoreXmlInject(self, __a0: unicode, __a1: unicode, __a2: int, __a3: ghidra.xml.XmlPullParser) -> ghidra.program.model.lang.InjectPayload: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
