import ghidra.feature.vt.gui.filters
import ghidra.feature.vt.gui.provider.matchtable
import ghidra.framework.options
import java.lang
import javax.swing


class AbstractAddressRangeFilter(ghidra.feature.vt.gui.filters.AncillaryFilter, ghidra.feature.vt.gui.provider.matchtable.NumberRangeSubFilterChecker, ghidra.feature.vt.gui.provider.matchtable.NumberRangeProducer):








    def addFilterChangedListener(self, __a0: ghidra.feature.vt.gui.filters.FilterChangedListener) -> None: ...

    def addFilterStatusListener(self, __a0: ghidra.feature.vt.gui.filters.FilterStatusListener) -> None: ...

    def clearFilter(self) -> None: ...

    def createCopy(self) -> ghidra.feature.vt.gui.filters.Filter: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def fireFilterStateChanged(self) -> None: ...

    def getClass(self) -> java.lang.Class: ...

    def getComponent(self) -> javax.swing.JComponent: ...

    def getFilterShortcutState(self) -> ghidra.feature.vt.gui.filters.Filter.FilterShortcutState: ...

    def getFilterState(self) -> ghidra.feature.vt.gui.filters.FilterState: ...

    def getFilterStatus(self) -> ghidra.feature.vt.gui.filters.Filter.FilterEditingStatus: ...

    def getLowerNumber(self) -> java.lang.Number: ...

    def getUpperNumber(self) -> java.lang.Number: ...

    def hashCode(self) -> int: ...

    @overload
    def isSubFilterOf(self, __a0: ghidra.feature.vt.gui.filters.Filter) -> bool: ...

    @overload
    def isSubFilterOf(self, __a0: ghidra.feature.vt.gui.provider.matchtable.NumberRangeProducer, __a1: ghidra.feature.vt.gui.provider.matchtable.NumberRangeProducer) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def passesFilter(self, __a0: object) -> bool: ...

    def readConfigState(self, __a0: ghidra.framework.options.SaveState) -> None: ...

    def removeFilterChangedListener(self, __a0: ghidra.feature.vt.gui.filters.FilterChangedListener) -> None: ...

    def restoreFilterState(self, __a0: ghidra.feature.vt.gui.filters.FilterState) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def writeConfigState(self, __a0: ghidra.framework.options.SaveState) -> None: ...

    @property
    def component(self) -> javax.swing.JComponent: ...

    @property
    def filterShortcutState(self) -> ghidra.feature.vt.gui.filters.Filter.FilterShortcutState: ...

    @property
    def filterState(self) -> ghidra.feature.vt.gui.filters.FilterState: ...

    @property
    def filterStatus(self) -> ghidra.feature.vt.gui.filters.Filter.FilterEditingStatus: ...

    @property
    def lowerNumber(self) -> java.lang.Number: ...

    @property
    def upperNumber(self) -> java.lang.Number: ...
