import java.lang
import javax.swing


class BoundedRangeInputVerifier(javax.swing.InputVerifier):




    def __init__(self, __a0: javax.swing.JFormattedTextField, __a1: bool, __a2: java.lang.Number, __a3: java.lang.Number): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    @overload
    def shouldYieldFocus(self, __a0: javax.swing.JComponent) -> bool: ...

    @overload
    def shouldYieldFocus(self, __a0: javax.swing.JComponent, __a1: javax.swing.JComponent) -> bool: ...

    def toString(self) -> unicode: ...

    def verify(self, __a0: javax.swing.JComponent) -> bool: ...

    def verifyTarget(self, __a0: javax.swing.JComponent) -> bool: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
