import java.lang
import javax.swing


class CheckBoxInfo(object):




    def __init__(self, __a0: javax.swing.JCheckBox): ...



    def equals(self, __a0: object) -> bool: ...

    def getCheckBox(self) -> javax.swing.JCheckBox: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def isSelected(self) -> bool: ...

    def matchesStatus(self, __a0: object) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setSelected(self, __a0: bool) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def checkBox(self) -> javax.swing.JCheckBox: ...

    @property
    def selected(self) -> bool: ...

    @selected.setter
    def selected(self, value: bool) -> None: ...
