import ghidra.feature.vt.gui.filters
import java.lang


class FilterState(object):




    def __init__(self, __a0: ghidra.feature.vt.gui.filters.Filter): ...



    def equals(self, __a0: object) -> bool: ...

    def get(self, __a0: object) -> object: ...

    def getClass(self) -> java.lang.Class: ...

    def getFilter(self) -> ghidra.feature.vt.gui.filters.Filter: ...

    def hashCode(self) -> int: ...

    def isSame(self, __a0: ghidra.feature.vt.gui.filters.FilterState) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def put(self, __a0: object, __a1: object) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def filter(self) -> ghidra.feature.vt.gui.filters.Filter: ...
