from .ClipboardPlugin import ClipboardPlugin as ClipboardPlugin
from .CodeBrowserClipboardProvider import CodeBrowserClipboardProvider as CodeBrowserClipboardProvider
from .CopyPasteSpecialDialog import CopyPasteSpecialDialog as CopyPasteSpecialDialog
