import ghidra.feature.vt.gui.provider.relatedMatches
import ghidra.program.model.address
import ghidra.program.model.listing
import java.lang


class VTRelatedMatch(object):








    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getCorrelation(self) -> ghidra.feature.vt.gui.provider.relatedMatches.VTRelatedMatchType: ...

    def getDestinationAddress(self) -> ghidra.program.model.address.Address: ...

    def getDestinationFunction(self) -> ghidra.program.model.listing.Function: ...

    def getSourceAddress(self) -> ghidra.program.model.address.Address: ...

    def getSourceFunction(self) -> ghidra.program.model.listing.Function: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def correlation(self) -> ghidra.feature.vt.gui.provider.relatedMatches.VTRelatedMatchType: ...

    @property
    def destinationAddress(self) -> ghidra.program.model.address.Address: ...

    @property
    def destinationFunction(self) -> ghidra.program.model.listing.Function: ...

    @property
    def sourceAddress(self) -> ghidra.program.model.address.Address: ...

    @property
    def sourceFunction(self) -> ghidra.program.model.listing.Function: ...
