import ghidra.framework.main.datatable
import ghidra.framework.model
import java.lang
import java.util
import javax.swing


class DomainFileInfo(object):




    def __init__(self, domainFile: ghidra.framework.model.DomainFile): ...



    def clearMetaCache(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDisplayName(self) -> unicode: ...

    def getDomainFile(self) -> ghidra.framework.model.DomainFile: ...

    def getDomainFileType(self) -> ghidra.framework.main.datatable.DomainFileType: ...

    def getIcon(self) -> javax.swing.Icon: ...

    def getMetaDataValue(self, key: unicode) -> unicode: ...

    def getModificationDate(self) -> java.util.Date: ...

    def getName(self) -> unicode: ...

    def getPath(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def refresh(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def displayName(self) -> unicode: ...

    @property
    def domainFile(self) -> ghidra.framework.model.DomainFile: ...

    @property
    def domainFileType(self) -> ghidra.framework.main.datatable.DomainFileType: ...

    @property
    def icon(self) -> javax.swing.Icon: ...

    @property
    def modificationDate(self) -> java.util.Date: ...

    @property
    def name(self) -> unicode: ...

    @property
    def path(self) -> unicode: ...
