import docking.widgets.table
import ghidra.framework.main.datatable
import java.lang
import javax.swing


class DomainFileType(object, java.lang.Comparable, docking.widgets.table.DisplayStringProvider):




    def __init__(self, contentType: unicode, icon: javax.swing.Icon, isVersioned: bool): ...



    @overload
    def compareTo(self, other: ghidra.framework.main.datatable.DomainFileType) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getContentType(self) -> unicode: ...

    def getDisplayString(self) -> unicode: ...

    def getIcon(self) -> javax.swing.Icon: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def contentType(self) -> unicode: ...

    @property
    def displayString(self) -> unicode: ...

    @property
    def icon(self) -> javax.swing.Icon: ...
