import java.awt.dnd
import java.lang


class ProjectDataTableDnDHandler(object, java.awt.dnd.DragSourceListener, java.awt.dnd.DragGestureListener):
    selectedData: List[object]







    def dragDropEnd(self, dsde: java.awt.dnd.DragSourceDropEvent) -> None: ...

    def dragEnter(self, dsde: java.awt.dnd.DragSourceDragEvent) -> None: ...

    def dragExit(self, dse: java.awt.dnd.DragSourceEvent) -> None: ...

    def dragGestureRecognized(self, dragEvent: java.awt.dnd.DragGestureEvent) -> None: ...

    def dragOver(self, dsde: java.awt.dnd.DragSourceDragEvent) -> None: ...

    def dropActionChanged(self, dsde: java.awt.dnd.DragSourceDragEvent) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
