import docking
import ghidra.app.nav
import ghidra.app.plugin.core.functiongraph.action
import ghidra.graph.viewer
import ghidra.program.model.address
import ghidra.program.model.listing
import ghidra.program.util
import java.awt
import java.awt.event
import java.lang
import java.util


class FunctionGraphVertexLocationInFullViewModeActionContext(ghidra.app.plugin.core.functiongraph.action.FunctionGraphEditableVertexLocationActionContext):




    def __init__(self, __a0: ghidra.app.plugin.core.functiongraph.FGProvider, __a1: ghidra.app.plugin.core.functiongraph.graph.vertex.FGVertex): ...



    def equals(self, __a0: object) -> bool: ...

    def getAddress(self) -> ghidra.program.model.address.Address: ...

    def getClass(self) -> java.lang.Class: ...

    def getCodeUnit(self) -> ghidra.program.model.listing.CodeUnit: ...

    def getComponentProvider(self) -> docking.ComponentProvider: ...

    def getContextObject(self) -> object: ...

    def getGlobalContext(self) -> docking.ActionContext: ...

    def getHighlight(self) -> ghidra.program.util.ProgramSelection: ...

    def getLocation(self) -> ghidra.program.util.ProgramLocation: ...

    def getMouseEvent(self) -> java.awt.event.MouseEvent: ...

    def getNavigatable(self) -> ghidra.app.nav.Navigatable: ...

    def getProgram(self) -> ghidra.program.model.listing.Program: ...

    def getSelectedVertices(self) -> java.util.Set: ...

    def getSelection(self) -> ghidra.program.util.ProgramSelection: ...

    def getSourceComponent(self) -> java.awt.Component: ...

    def getSourceObject(self) -> object: ...

    def getVertex(self) -> ghidra.graph.viewer.VisualVertex: ...

    def getVertexInfo(self) -> ghidra.app.plugin.core.functiongraph.action.VertexActionContextInfo: ...

    def hasHighlight(self) -> bool: ...

    def hasSelection(self) -> bool: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setContextObject(self, __a0: object) -> docking.ActionContext: ...

    def setMouseEvent(self, __a0: java.awt.event.MouseEvent) -> docking.ActionContext: ...

    def setSourceObject(self, __a0: object) -> docking.ActionContext: ...

    def shouldShowSatelliteActions(self) -> bool: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
