from typing import List
import ghidra.app.util.demangler
import ghidra.program.model.data
import java.lang


class DemangledTemplate(object):




    def __init__(self): ...



    def addParameter(self, parameter: ghidra.app.util.demangler.DemangledDataType) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDataType(self, defaultPointerSize: int) -> ghidra.program.model.data.DataType: ...

    def getParameters(self) -> List[ghidra.app.util.demangler.DemangledDataType]: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    def toTemplate(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def parameters(self) -> List[object]: ...
