from typing import List
import ghidra.framework.task.gui
import java.lang
import java.util
import javax.swing.event


class CompletedTaskListModel(ghidra.framework.task.gui.GTaskListModel):








    def addListDataListener(self, __a0: javax.swing.event.ListDataListener) -> None: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getElementAt(self, index: int) -> ghidra.framework.task.gui.GTaskResultInfo: ...

    def getListDataListeners(self) -> List[javax.swing.event.ListDataListener]: ...

    def getListeners(self, __a0: java.lang.Class) -> List[java.util.EventListener]: ...

    def getSize(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def removeListDataListener(self, __a0: javax.swing.event.ListDataListener) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def size(self) -> int: ...
