from typing import List
import docking.widgets.tree
import docking.widgets.tree.support
import java.awt.datatransfer
import java.lang


class SymbolGTreeDragNDropHandler(object, docking.widgets.tree.support.GTreeDragNDropHandler):








    def drop(self, __a0: docking.widgets.tree.GTreeNode, __a1: java.awt.datatransfer.Transferable, __a2: int) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getSupportedDataFlavors(self, __a0: List[object]) -> List[java.awt.datatransfer.DataFlavor]: ...

    def getSupportedDragActions(self) -> int: ...

    def getTransferData(self, __a0: List[object], __a1: java.awt.datatransfer.DataFlavor) -> object: ...

    def hashCode(self) -> int: ...

    def isDropSiteOk(self, __a0: docking.widgets.tree.GTreeNode, __a1: List[java.awt.datatransfer.DataFlavor], __a2: int) -> bool: ...

    def isStartDragOk(self, __a0: List[object], __a1: int) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def supportedDragActions(self) -> int: ...
