import ghidra.graph.viewer.renderer
import java.awt
import java.lang


class MouseDraggedPaintableShape(ghidra.graph.viewer.renderer.PaintableShape):




    def __init__(self, start: java.awt.Point, end: java.awt.Point, tx: float, ty: float): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getColor(self) -> java.awt.Color: ...

    def getShape(self) -> java.awt.Shape: ...

    def getStroke(self) -> java.awt.Stroke: ...

    def getTx(self) -> float: ...

    def getTy(self) -> float: ...

    def hashCode(self) -> int: ...

    def isShapeFinished(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def paint(self, g: java.awt.Graphics2D) -> None: ...

    def setPoints(self, start: java.awt.Point, end: java.awt.Point) -> None: ...

    def shapeFinished(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
