import docking.widgets.fieldpanel.field
import docking.widgets.fieldpanel.internal
import docking.widgets.fieldpanel.support
import java.awt
import java.lang
import javax.swing


class ByteField(docking.widgets.fieldpanel.field.SimpleTextField):




    def __init__(self, __a0: unicode, __a1: java.awt.FontMetrics, __a2: int, __a3: int, __a4: bool, __a5: int, __a6: long, __a7: docking.widgets.fieldpanel.support.HighlightFactory): ...



    def contains(self, __a0: int, __a1: int) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getCol(self, __a0: int, __a1: int) -> int: ...

    def getCursorBounds(self, __a0: int, __a1: int) -> java.awt.Rectangle: ...

    def getFieldOffset(self) -> int: ...

    def getFontMetrics(self) -> java.awt.FontMetrics: ...

    def getForeground(self) -> java.awt.Color: ...

    def getHeight(self) -> int: ...

    def getHeightAbove(self) -> int: ...

    def getHeightBelow(self) -> int: ...

    def getIndex(self) -> long: ...

    def getNumCols(self, __a0: int) -> int: ...

    def getNumRows(self) -> int: ...

    def getPreferredWidth(self) -> int: ...

    def getRow(self, __a0: int) -> int: ...

    def getScrollableUnitIncrement(self, __a0: int, __a1: int, __a2: int) -> int: ...

    def getStartX(self) -> int: ...

    def getText(self) -> unicode: ...

    def getTextWithLineSeparators(self) -> unicode: ...

    def getWidth(self) -> int: ...

    def getX(self, __a0: int, __a1: int) -> int: ...

    def getY(self, __a0: int) -> int: ...

    def hashCode(self) -> int: ...

    def isAllowCursorAtEnd(self) -> bool: ...

    def isPrimary(self) -> bool: ...

    def isValid(self, __a0: int, __a1: int) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def paint(self, __a0: javax.swing.JComponent, __a1: java.awt.Graphics, __a2: docking.widgets.fieldpanel.internal.PaintContext, __a3: java.awt.Rectangle, __a4: docking.widgets.fieldpanel.internal.FieldBackgroundColorManager, __a5: docking.widgets.fieldpanel.support.RowColLocation, __a6: int) -> None: ...

    def rowHeightChanged(self, __a0: int, __a1: int) -> None: ...

    def screenLocationToTextOffset(self, __a0: int, __a1: int) -> int: ...

    def setFontMetrics(self, __a0: java.awt.FontMetrics) -> None: ...

    def setForeground(self, __a0: java.awt.Color) -> None: ...

    def setPrimary(self, __a0: bool) -> None: ...

    def textOffsetToScreenLocation(self, __a0: int) -> docking.widgets.fieldpanel.support.RowColLocation: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def fieldOffset(self) -> int: ...

    @property
    def index(self) -> long: ...
