from typing import List
import java.lang
import java.util


class PythonPluginInputThread(java.lang.Thread):
    """
    Thread responsible for getting interactive lines of python from the plugin.
     This class also kicks off the execution of that line in a new PythonPluginExecutionThread.
    """





    @overload
    def __init__(self): ...

    @overload
    def __init__(self, __a0: unicode): ...

    @overload
    def __init__(self, __a0: java.lang.Runnable): ...

    @overload
    def __init__(self, __a0: java.lang.Runnable, __a1: unicode): ...

    @overload
    def __init__(self, __a0: java.lang.ThreadGroup, __a1: unicode): ...

    @overload
    def __init__(self, __a0: java.lang.ThreadGroup, __a1: java.lang.Runnable): ...

    @overload
    def __init__(self, __a0: java.lang.ThreadGroup, __a1: java.lang.Runnable, __a2: unicode): ...

    @overload
    def __init__(self, __a0: java.lang.ThreadGroup, __a1: java.lang.Runnable, __a2: unicode, __a3: long): ...

    @overload
    def __init__(self, __a0: java.lang.ThreadGroup, __a1: java.lang.Runnable, __a2: unicode, __a3: long, __a4: bool): ...



    @staticmethod
    def activeCount() -> int: ...

    def checkAccess(self) -> None: ...

    def countStackFrames(self) -> int: ...

    @staticmethod
    def currentThread() -> java.lang.Thread: ...

    @staticmethod
    def dumpStack() -> None: ...

    @staticmethod
    def enumerate(__a0: List[java.lang.Thread]) -> int: ...

    def equals(self, __a0: object) -> bool: ...

    @staticmethod
    def getAllStackTraces() -> java.util.Map: ...

    def getClass(self) -> java.lang.Class: ...

    def getContextClassLoader(self) -> java.lang.ClassLoader: ...

    @staticmethod
    def getDefaultUncaughtExceptionHandler() -> java.lang.Thread.UncaughtExceptionHandler: ...

    def getId(self) -> long: ...

    def getName(self) -> unicode: ...

    def getPriority(self) -> int: ...

    def getStackTrace(self) -> List[java.lang.StackTraceElement]: ...

    def getState(self) -> java.lang.Thread.State: ...

    def getThreadGroup(self) -> java.lang.ThreadGroup: ...

    def getUncaughtExceptionHandler(self) -> java.lang.Thread.UncaughtExceptionHandler: ...

    def hashCode(self) -> int: ...

    @staticmethod
    def holdsLock(__a0: object) -> bool: ...

    def interrupt(self) -> None: ...

    @staticmethod
    def interrupted() -> bool: ...

    def isAlive(self) -> bool: ...

    def isDaemon(self) -> bool: ...

    def isInterrupted(self) -> bool: ...

    @overload
    def join(self) -> None: ...

    @overload
    def join(self, __a0: long) -> None: ...

    @overload
    def join(self, __a0: long, __a1: int) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    @staticmethod
    def onSpinWait() -> None: ...

    def resume(self) -> None: ...

    def run(self) -> None: ...

    def setContextClassLoader(self, __a0: java.lang.ClassLoader) -> None: ...

    def setDaemon(self, __a0: bool) -> None: ...

    @staticmethod
    def setDefaultUncaughtExceptionHandler(__a0: java.lang.Thread.UncaughtExceptionHandler) -> None: ...

    def setName(self, __a0: unicode) -> None: ...

    def setPriority(self, __a0: int) -> None: ...

    def setUncaughtExceptionHandler(self, __a0: java.lang.Thread.UncaughtExceptionHandler) -> None: ...

    @overload
    @staticmethod
    def sleep(__a0: long) -> None: ...

    @overload
    @staticmethod
    def sleep(__a0: long, __a1: int) -> None: ...

    def start(self) -> None: ...

    def stop(self) -> None: ...

    def suspend(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @staticmethod
    def yield() -> None: ...
