import java.lang
import org.antlr.runtime


class LexerMultiplexer(object, org.antlr.runtime.TokenSource):




    def __init__(self, modes: List[org.antlr.runtime.TokenSource]): ...



    def channelOff(self, channel: int) -> None: ...

    def channelOn(self, channel: int) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getSourceName(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def nextToken(self) -> org.antlr.runtime.Token: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def popMode(self) -> int: ...

    def pushMode(self, mode: int) -> None: ...

    def setMode(self, mode: int) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def mode(self) -> None: ...  # No getter available.

    @mode.setter
    def mode(self, value: int) -> None: ...

    @property
    def sourceName(self) -> unicode: ...
