import ghidra.sleigh.grammar
import java.lang


class Locator(object):




    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getLocation(self, expandedLineNo: int) -> ghidra.sleigh.grammar.Location: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def registerLocation(self, expandedLineNo: int, realLocation: ghidra.sleigh.grammar.Location) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
