from typing import List
import java.lang


class IncludeFileFinder(object):




    def __init__(self, __a0: java.io.File): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getIncludeFileRoots(self, __a0: bool) -> List[object]: ...

    def getIncludeFiles(self, __a0: bool) -> List[object]: ...

    def hashCode(self) -> int: ...

    @staticmethod
    def main(__a0: List[unicode]) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
