from typing import List
import ghidra.file.formats.iso9660
import ghidra.program.model.data
import java.lang


class ISO9660VolumeDescriptor(ghidra.file.formats.iso9660.ISO9660BaseVolume):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader): ...



    def equals(self, __a0: object) -> bool: ...

    def getAbstractFileIdentifier(self) -> List[int]: ...

    def getApplicationIdentifier(self) -> List[int]: ...

    def getApplicationUsed(self) -> List[int]: ...

    def getBibliographicFileIdentifier(self) -> List[int]: ...

    def getClass(self) -> java.lang.Class: ...

    def getCopyrightFileIdentifier(self) -> List[int]: ...

    def getDataPreparerIdentifier(self) -> List[int]: ...

    def getDirectoryEntry(self) -> ghidra.file.formats.iso9660.ISO9660Directory: ...

    def getFileStructureVersion(self) -> int: ...

    def getIdentifier(self) -> List[int]: ...

    def getLogicalBlockSizeBE(self) -> int: ...

    def getLogicalBlockSizeLE(self) -> int: ...

    def getOptionalTypeLPathTableLocation(self) -> int: ...

    def getOptionalTypeMPathTableLocation(self) -> int: ...

    def getPathTableSizeBE(self) -> int: ...

    def getPathTableSizeLE(self) -> int: ...

    def getPublisherIdentifier(self) -> List[int]: ...

    def getReserved(self) -> List[int]: ...

    def getSystemIdentifier(self) -> List[int]: ...

    def getTypeCode(self) -> int: ...

    def getTypeCodeString(self) -> unicode: ...

    def getTypeLPathTableLocation(self) -> int: ...

    def getTypeMPathTableLocation(self) -> int: ...

    def getUnused(self) -> int: ...

    def getUnused2(self) -> long: ...

    def getUnused3(self) -> List[int]: ...

    def getUnused4(self) -> int: ...

    def getVersion(self) -> int: ...

    def getVolumeCreationDateTime(self) -> List[int]: ...

    def getVolumeEffectiveDateTime(self) -> List[int]: ...

    def getVolumeExpirationDateTime(self) -> List[int]: ...

    def getVolumeIdentifier(self) -> List[int]: ...

    def getVolumeIndex(self) -> long: ...

    def getVolumeModifyDateTime(self) -> List[int]: ...

    def getVolumeSeqNumberBE(self) -> int: ...

    def getVolumeSeqNumberLE(self) -> int: ...

    def getVolumeSetIdentifier(self) -> List[int]: ...

    def getVolumeSetSizeBE(self) -> int: ...

    def getVolumeSetSizeLE(self) -> int: ...

    def getVolumeSpaceSizeBE(self) -> int: ...

    def getVolumeSpaceSizeLE(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def abstractFileIdentifier(self) -> List[int]: ...

    @property
    def applicationIdentifier(self) -> List[int]: ...

    @property
    def applicationUsed(self) -> List[int]: ...

    @property
    def bibliographicFileIdentifier(self) -> List[int]: ...

    @property
    def copyrightFileIdentifier(self) -> List[int]: ...

    @property
    def dataPreparerIdentifier(self) -> List[int]: ...

    @property
    def directoryEntry(self) -> ghidra.file.formats.iso9660.ISO9660Directory: ...

    @property
    def fileStructureVersion(self) -> int: ...

    @property
    def logicalBlockSizeBE(self) -> int: ...

    @property
    def logicalBlockSizeLE(self) -> int: ...

    @property
    def optionalTypeLPathTableLocation(self) -> int: ...

    @property
    def optionalTypeMPathTableLocation(self) -> int: ...

    @property
    def pathTableSizeBE(self) -> int: ...

    @property
    def pathTableSizeLE(self) -> int: ...

    @property
    def publisherIdentifier(self) -> List[int]: ...

    @property
    def reserved(self) -> List[int]: ...

    @property
    def systemIdentifier(self) -> List[int]: ...

    @property
    def typeLPathTableLocation(self) -> int: ...

    @property
    def typeMPathTableLocation(self) -> int: ...

    @property
    def unused(self) -> int: ...

    @property
    def unused2(self) -> long: ...

    @property
    def unused3(self) -> List[int]: ...

    @property
    def unused4(self) -> int: ...

    @property
    def volumeCreationDateTime(self) -> List[int]: ...

    @property
    def volumeEffectiveDateTime(self) -> List[int]: ...

    @property
    def volumeExpirationDateTime(self) -> List[int]: ...

    @property
    def volumeIdentifier(self) -> List[int]: ...

    @property
    def volumeModifyDateTime(self) -> List[int]: ...

    @property
    def volumeSeqNumberBE(self) -> int: ...

    @property
    def volumeSeqNumberLE(self) -> int: ...

    @property
    def volumeSetIdentifier(self) -> List[int]: ...

    @property
    def volumeSetSizeBE(self) -> int: ...

    @property
    def volumeSetSizeLE(self) -> int: ...

    @property
    def volumeSpaceSizeBE(self) -> int: ...

    @property
    def volumeSpaceSizeLE(self) -> int: ...
