import ghidra.app.util
import ghidra.program.model.data
import java.lang


class PdbCategories(object):




    def __init__(self, __a0: unicode, __a1: List[object]): ...



    def equals(self, __a0: object) -> bool: ...

    def getAnonymousFunctionsCategory(self) -> ghidra.program.model.data.CategoryPath: ...

    def getAnonymousTypesCategory(self) -> ghidra.program.model.data.CategoryPath: ...

    def getCategory(self, __a0: ghidra.app.util.SymbolPath) -> ghidra.program.model.data.CategoryPath: ...

    def getClass(self) -> java.lang.Class: ...

    def getRootCategoryPath(self) -> ghidra.program.model.data.CategoryPath: ...

    def getTypedefsCategory(self, __a0: int, __a1: ghidra.app.util.SymbolPath) -> ghidra.program.model.data.CategoryPath: ...

    def getUnCategorizedCategoryPath(self) -> ghidra.program.model.data.CategoryPath: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def anonymousFunctionsCategory(self) -> ghidra.program.model.data.CategoryPath: ...

    @property
    def anonymousTypesCategory(self) -> ghidra.program.model.data.CategoryPath: ...

    @property
    def rootCategoryPath(self) -> ghidra.program.model.data.CategoryPath: ...

    @property
    def unCategorizedCategoryPath(self) -> ghidra.program.model.data.CategoryPath: ...
