from typing import List
import java.lang


class PdbProgramAttributes(object):




    @overload
    def __init__(self, __a0: ghidra.program.model.listing.Program): ...

    @overload
    def __init__(self, __a0: unicode, __a1: unicode, __a2: bool, __a3: bool, __a4: unicode, __a5: unicode, __a6: unicode): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getExecutablePath(self) -> unicode: ...

    def getGuidAgeCombo(self) -> unicode: ...

    def getPdbAge(self) -> unicode: ...

    def getPdbFile(self) -> unicode: ...

    def getPdbGuid(self) -> unicode: ...

    def getPdbSignature(self) -> unicode: ...

    def getPdbVersion(self) -> unicode: ...

    def getPotentialPdbFilenames(self) -> List[object]: ...

    def hashCode(self) -> int: ...

    def isPdbLoaded(self) -> bool: ...

    def isProgramAnalyzed(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def executablePath(self) -> unicode: ...

    @property
    def guidAgeCombo(self) -> unicode: ...

    @property
    def pdbAge(self) -> unicode: ...

    @property
    def pdbFile(self) -> unicode: ...

    @property
    def pdbGuid(self) -> unicode: ...

    @property
    def pdbLoaded(self) -> bool: ...

    @property
    def pdbSignature(self) -> unicode: ...

    @property
    def pdbVersion(self) -> unicode: ...

    @property
    def potentialPdbFilenames(self) -> List[object]: ...

    @property
    def programAnalyzed(self) -> bool: ...
