from typing import List
import ghidra.app.plugin.core.compositeeditor
import java.lang


class CompositeEditorActionManager(object):




    def __init__(self, __a0: ghidra.app.plugin.core.compositeeditor.CompositeEditorProvider): ...



    def addEditorActionListener(self, __a0: ghidra.app.plugin.core.compositeeditor.EditorActionListener) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getAllActions(self) -> List[ghidra.app.plugin.core.compositeeditor.CompositeEditorTableAction]: ...

    def getClass(self) -> java.lang.Class: ...

    def getCycleGroupActions(self) -> List[ghidra.app.plugin.core.compositeeditor.CompositeEditorTableAction]: ...

    def getEditorActions(self) -> List[ghidra.app.plugin.core.compositeeditor.CompositeEditorTableAction]: ...

    def getFavoritesActions(self) -> List[ghidra.app.plugin.core.compositeeditor.CompositeEditorTableAction]: ...

    def getNamedAction(self, __a0: unicode) -> ghidra.app.plugin.core.compositeeditor.CompositeEditorTableAction: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def removeEditorActionListener(self, __a0: ghidra.app.plugin.core.compositeeditor.EditorActionListener) -> None: ...

    def setEditorActions(self, __a0: List[ghidra.app.plugin.core.compositeeditor.CompositeEditorTableAction]) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def allActions(self) -> List[ghidra.app.plugin.core.compositeeditor.CompositeEditorTableAction]: ...

    @property
    def cycleGroupActions(self) -> List[ghidra.app.plugin.core.compositeeditor.CompositeEditorTableAction]: ...

    @property
    def editorActions(self) -> List[ghidra.app.plugin.core.compositeeditor.CompositeEditorTableAction]: ...

    @editorActions.setter
    def editorActions(self, value: List[ghidra.app.plugin.core.compositeeditor.CompositeEditorTableAction]) -> None: ...

    @property
    def favoritesActions(self) -> List[ghidra.app.plugin.core.compositeeditor.CompositeEditorTableAction]: ...
