from typing import List
import ghidra.server
import java.lang
import javax.security.auth
import javax.security.auth.callback


class SSHAuthenticationModule(object):




    def __init__(self, __a0: bool): ...



    def addAuthenticationCallbacks(self, __a0: List[javax.security.auth.callback.Callback]) -> List[javax.security.auth.callback.Callback]: ...

    def allowsNameCallback(self) -> bool: ...

    def authenticate(self, __a0: ghidra.server.UserManager, __a1: javax.security.auth.Subject, __a2: List[javax.security.auth.callback.Callback]) -> unicode: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hasSignedSSHCallback(self, __a0: List[javax.security.auth.callback.Callback]) -> bool: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
