import ghidra.feature.vt.api.main
import ghidra.feature.vt.gui.plugin
import ghidra.feature.vt.gui.util
import java.lang


class MatchInfoFactory(object):




    def __init__(self): ...



    def clearCache(self) -> None: ...

    def clearCacheForAssociation(self, __a0: ghidra.feature.vt.api.main.VTAssociation) -> None: ...

    def clearMatchInfoInternalCache(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getMatchInfo(self, __a0: ghidra.feature.vt.gui.plugin.VTController, __a1: ghidra.feature.vt.api.main.VTMatch, __a2: ghidra.feature.vt.gui.plugin.AddressCorrelatorManager) -> ghidra.feature.vt.gui.util.MatchInfo: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
