import ghidra.program.model.address
import ghidra.program.model.lang
import ghidra.program.model.listing
import ghidra.program.util
import ghidra.util.task
import java.lang


class SimpleLanguageTranslator(ghidra.program.util.LanguageTranslatorAdapter):
    """
    SimpleLanguageTranslator provides a simple translator which
     derives its mappings from an XML translation specification file.
    """









    def equals(self, __a0: object) -> bool: ...

    def fixupInstructions(self, program: ghidra.program.model.listing.Program, oldLanguage: ghidra.program.model.lang.Language, monitor: ghidra.util.task.TaskMonitor) -> None: ...

    def getClass(self) -> java.lang.Class: ...

    def getNewAddressSpace(self, oldSpaceName: unicode) -> ghidra.program.model.address.AddressSpace: ...

    def getNewCompilerSpecID(self, oldCompilerSpecID: ghidra.program.model.lang.CompilerSpecID) -> ghidra.program.model.lang.CompilerSpecID: ...

    def getNewContextRegister(self) -> ghidra.program.model.lang.Register: ...

    def getNewLanguage(self) -> ghidra.program.model.lang.Language: ...

    def getNewLanguageID(self) -> ghidra.program.model.lang.LanguageID: ...

    def getNewRegister(self, oldReg: ghidra.program.model.lang.Register) -> ghidra.program.model.lang.Register: ...

    def getNewRegisterValue(self, oldRegisterValue: ghidra.program.model.lang.RegisterValue) -> ghidra.program.model.lang.RegisterValue: ...

    def getNewVersion(self) -> int: ...

    def getOldCompilerSpec(self, oldCompilerSpecID: ghidra.program.model.lang.CompilerSpecID) -> ghidra.program.model.lang.CompilerSpec: ...

    def getOldContextRegister(self) -> ghidra.program.model.lang.Register: ...

    def getOldLanguage(self) -> ghidra.program.model.lang.Language: ...

    def getOldLanguageID(self) -> ghidra.program.model.lang.LanguageID: ...

    def getOldRegister(self, oldAddr: ghidra.program.model.address.Address, size: int) -> ghidra.program.model.lang.Register: ...

    def getOldRegisterContaining(self, oldAddr: ghidra.program.model.address.Address) -> ghidra.program.model.lang.Register: ...

    def getOldVersion(self) -> int: ...

    def hashCode(self) -> int: ...

    def isValid(self) -> bool: ...

    def isValueTranslationRequired(self, oldReg: ghidra.program.model.lang.Register) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
