import java.awt
import java.lang
import java.util


class Palette(object):




    def __init__(self, __a0: int, __a1: java.awt.Color): ...



    def addKnot(self, __a0: unicode, __a1: java.awt.Color, __a2: int, __a3: int) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getColor(self, __a0: int) -> java.awt.Color: ...

    def getKnots(self) -> java.util.ArrayList: ...

    def getSize(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setBase(self, __a0: java.awt.Color, __a1: java.awt.Color) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def knots(self) -> java.util.ArrayList: ...

    @property
    def size(self) -> int: ...
