import java.lang


class SearchOptions(object, java.lang.Cloneable):




    def __init__(self, __a0: unicode, __a1: bool, __a2: bool, __a3: bool, __a4: bool, __a5: bool, __a6: bool, __a7: bool, __a8: bool, __a9: bool, __a10: bool, __a11: bool, __a12: bool): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getText(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def isCaseSensitive(self) -> bool: ...

    def isForward(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def searchBothDataMnemonicsAndOperands(self) -> bool: ...

    def searchBothInstructionMnemonicAndOperands(self) -> bool: ...

    def searchComments(self) -> bool: ...

    def searchDataMnemonics(self) -> bool: ...

    def searchDataOperands(self) -> bool: ...

    def searchFunctions(self) -> bool: ...

    def searchInstructionMnemonics(self) -> bool: ...

    def searchInstructionOperands(self) -> bool: ...

    def searchLabels(self) -> bool: ...

    def searchOnlyDataMnemonics(self) -> bool: ...

    def searchOnlyDataOperands(self) -> bool: ...

    def searchOnlyInstructionMnemonics(self) -> bool: ...

    def searchOnlyInstructionOperands(self) -> bool: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def caseSensitive(self) -> bool: ...

    @property
    def forward(self) -> bool: ...

    @property
    def text(self) -> unicode: ...
