import java.lang


class CodeUnitSearchInfo(object):




    def __init__(self, searchInstructions: bool, searchDefinedData: bool, searchUndefinedData: bool): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def isSearchDefinedData(self) -> bool: ...

    def isSearchInstructions(self) -> bool: ...

    def isSearchUndefinedData(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def searchAll(self) -> bool: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def searchDefinedData(self) -> bool: ...

    @property
    def searchInstructions(self) -> bool: ...

    @property
    def searchUndefinedData(self) -> bool: ...
