from typing import List
import ghidra.app.util
import java.awt.datatransfer
import java.awt.dnd
import java.lang


class DataDropOnBrowserHandler(object, ghidra.app.util.ProgramDropProvider):




    def __init__(self, __a0: ghidra.app.plugin.core.datamgr.DataTypeManagerPlugin): ...



    def add(self, __a0: object, __a1: object, __a2: java.awt.datatransfer.DataFlavor) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDataFlavors(self) -> List[java.awt.datatransfer.DataFlavor]: ...

    def getPriority(self) -> int: ...

    def hashCode(self) -> int: ...

    def isDropOk(self, __a0: object, __a1: java.awt.dnd.DropTargetDragEvent) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def dataFlavors(self) -> List[java.awt.datatransfer.DataFlavor]: ...

    @property
    def priority(self) -> int: ...
