import ghidra.pcodeCPort.context
import ghidra.pcodeCPort.sleighbase
import ghidra.pcodeCPort.slghsymbol
import java.io
import java.lang
import org.jdom


class ContextOp(ghidra.pcodeCPort.slghsymbol.ContextChange):
    location: ghidra.sleigh.grammar.Location



    @overload
    def __init__(self, __a0: ghidra.sleigh.grammar.Location): ...

    @overload
    def __init__(self, __a0: ghidra.sleigh.grammar.Location, __a1: int, __a2: int, __a3: ghidra.pcodeCPort.slghpatexpress.PatternExpression): ...



    def apply(self, __a0: ghidra.pcodeCPort.context.ParserWalkerChange) -> None: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def restoreXml(self, __a0: org.jdom.Element, __a1: ghidra.pcodeCPort.sleighbase.SleighBase) -> None: ...

    def saveXml(self, __a0: java.io.PrintStream) -> None: ...

    def toString(self) -> unicode: ...

    def validate(self) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
