import ghidra.pcodeCPort.slghpattern
import ghidra.pcodeCPort.slghsymbol
import java.lang


class DecisionNode(object):




    @overload
    def __init__(self): ...

    @overload
    def __init__(self, __a0: ghidra.pcodeCPort.slghsymbol.DecisionNode): ...



    def addConstructorPair(self, __a0: ghidra.pcodeCPort.slghpattern.DisjointPattern, __a1: ghidra.pcodeCPort.slghsymbol.Constructor) -> None: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def orderPatterns(self, __a0: ghidra.pcodeCPort.slghsymbol.DecisionProperties) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
