import ghidra.pcodeCPort.sleighbase
import ghidra.pcodeCPort.slghsymbol
import ghidra.sleigh.grammar
import java.io
import java.lang
import org.jdom


class SectionSymbol(ghidra.pcodeCPort.slghsymbol.SleighSymbol):
    location: ghidra.sleigh.grammar.Location



    def __init__(self, __a0: ghidra.sleigh.grammar.Location, __a1: unicode, __a2: int): ...



    @overload
    def compareTo(self, __a0: ghidra.pcodeCPort.slghsymbol.SleighSymbol) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDefineCount(self) -> int: ...

    def getId(self) -> int: ...

    def getLocation(self) -> ghidra.sleigh.grammar.Location: ...

    def getName(self) -> unicode: ...

    def getRefCount(self) -> int: ...

    def getTemplateId(self) -> int: ...

    def getType(self) -> ghidra.pcodeCPort.slghsymbol.symbol_type: ...

    def hashCode(self) -> int: ...

    def incrementDefineCount(self) -> None: ...

    def incrementRefCount(self) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def restoreXml(self, __a0: org.jdom.Element, __a1: ghidra.pcodeCPort.sleighbase.SleighBase) -> None: ...

    def saveXml(self, __a0: java.io.PrintStream) -> None: ...

    def setLocation(self, __a0: ghidra.sleigh.grammar.Location) -> None: ...

    def setWasSought(self, __a0: bool) -> None: ...

    def toDetailedString(self) -> unicode: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def wasSought(self) -> bool: ...

    @property
    def defineCount(self) -> int: ...

    @property
    def refCount(self) -> int: ...

    @property
    def templateId(self) -> int: ...

    @property
    def type(self) -> ghidra.pcodeCPort.slghsymbol.symbol_type: ...
