from typing import List
import docking
import docking.action
import ghidra.app.nav
import ghidra.app.tablechooser
import ghidra.util
import ghidra.util.task
import java.awt
import java.awt.event
import java.lang
import java.util
import javax.swing
import utility.function


class MyTableChooserDialog(ghidra.app.tablechooser.TableChooserDialog):




    @overload
    def __init__(self, __a0: ghidra.app.plugin.core.table.TableServicePlugin, __a1: ghidra.app.tablechooser.TableChooserExecutor, __a2: ghidra.program.model.listing.Program, __a3: unicode, __a4: ghidra.app.nav.Navigatable): ...

    @overload
    def __init__(self, __a0: ghidra.app.plugin.core.table.TableServicePlugin, __a1: ghidra.app.tablechooser.TableChooserExecutor, __a2: ghidra.program.model.listing.Program, __a3: unicode, __a4: ghidra.app.nav.Navigatable, __a5: bool): ...



    def add(self, __a0: ghidra.app.tablechooser.AddressableRowObject) -> None: ...

    def addAction(self, __a0: docking.action.DockingActionIf) -> None: ...

    def addCustomColumn(self, __a0: ghidra.app.tablechooser.ColumnDisplay) -> None: ...

    def clearSelection(self) -> None: ...

    def clearStatusText(self) -> None: ...

    def close(self) -> None: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getActionContext(self, __a0: java.awt.event.MouseEvent) -> docking.ActionContext: ...

    def getActions(self) -> java.util.Set: ...

    def getBackground(self) -> java.awt.Color: ...

    def getClass(self) -> java.lang.Class: ...

    def getComponent(self) -> javax.swing.JComponent: ...

    def getDefaultButton(self) -> javax.swing.JButton: ...

    def getDefaultSize(self) -> java.awt.Dimension: ...

    def getFocusComponent(self) -> java.awt.Component: ...

    def getHelpLocatdion(self) -> ghidra.util.HelpLocation: ...

    def getIntialLocation(self) -> java.awt.Point: ...

    def getPreferredSize(self) -> java.awt.Dimension: ...

    def getRemberSize(self) -> bool: ...

    def getRememberLocation(self) -> bool: ...

    def getRowCount(self) -> int: ...

    def getSelectedRowObjects(self) -> List[object]: ...

    def getSelectedRows(self) -> List[int]: ...

    def getStatusText(self) -> unicode: ...

    def getTitle(self) -> unicode: ...

    def getUseSharedLocation(self) -> bool: ...

    def hashCode(self) -> int: ...

    def hideTaskMonitorComponent(self) -> None: ...

    def isBusy(self) -> bool: ...

    def isModal(self) -> bool: ...

    def isResizeable(self) -> bool: ...

    def isRunningTask(self) -> bool: ...

    def isShowing(self) -> bool: ...

    def isTransient(self) -> bool: ...

    def isVisible(self) -> bool: ...

    def navigatableRemoved(self, __a0: ghidra.app.nav.Navigatable) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def remove(self, __a0: ghidra.app.tablechooser.AddressableRowObject) -> None: ...

    def removeAction(self, __a0: docking.action.DockingActionIf) -> None: ...

    def selectRows(self, __a0: List[int]) -> None: ...

    def setBackground(self, __a0: java.awt.Color) -> None: ...

    def setClosedListener(self, __a0: utility.function.Callback) -> None: ...

    def setCursor(self, __a0: java.awt.Cursor) -> None: ...

    def setDefaultButton(self, __a0: javax.swing.JButton) -> None: ...

    def setDefaultSize(self, __a0: int, __a1: int) -> None: ...

    def setFocusComponent(self, __a0: java.awt.Component) -> None: ...

    def setHelpLocation(self, __a0: ghidra.util.HelpLocation) -> None: ...

    def setInitialLocation(self, __a0: int, __a1: int) -> None: ...

    def setMessage(self, __a0: unicode) -> None: ...

    @overload
    def setMinimumSize(self, __a0: java.awt.Dimension) -> None: ...

    @overload
    def setMinimumSize(self, __a0: int, __a1: int) -> None: ...

    def setPreferredSize(self, __a0: int, __a1: int) -> None: ...

    def setRememberLocation(self, __a0: bool) -> None: ...

    def setRememberSize(self, __a0: bool) -> None: ...

    def setResizable(self, __a0: bool) -> None: ...

    def setStatusJustification(self, __a0: int) -> None: ...

    @overload
    def setStatusText(self, __a0: unicode) -> None: ...

    @overload
    def setStatusText(self, __a0: unicode, __a1: ghidra.util.MessageType) -> None: ...

    @overload
    def setStatusText(self, __a0: unicode, __a1: ghidra.util.MessageType, __a2: bool) -> None: ...

    def setTitle(self, __a0: unicode) -> None: ...

    def setTransient(self, __a0: bool) -> None: ...

    def setUseSharedLocation(self, __a0: bool) -> None: ...

    def show(self) -> None: ...

    def showTaskMonitorComponent(self, __a0: unicode, __a1: bool, __a2: bool) -> ghidra.util.task.TaskMonitor: ...

    def taskCancelled(self, __a0: ghidra.util.task.Task) -> None: ...

    def taskCompleted(self, __a0: ghidra.util.task.Task) -> None: ...

    def toFront(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def waitForCurrentTask(self) -> None: ...
