from typing import List
import docking
import docking.action
import ghidra.app.plugin.core.strings
import ghidra.framework.plugintool
import ghidra.program.model.listing
import ghidra.program.util
import ghidra.util
import ghidra.util.table
import java.awt.event
import java.lang
import java.util.function
import javax.swing


class ViewStringsProvider(ghidra.framework.plugintool.ComponentProviderAdapter):
    ICON: javax.swing.ImageIcon = jar:file:/Applications/ghidra_9.2.1_PUBLIC/Ghidra/Features/Base/lib/Base.jar!/images/dataW.gif







    def addLocalAction(self, __a0: docking.action.DockingActionIf) -> None: ...

    def addToTool(self) -> None: ...

    def closeComponent(self) -> None: ...

    def componentActivated(self) -> None: ...

    def componentDeactived(self) -> None: ...

    def componentHidden(self) -> None: ...

    def componentShown(self) -> None: ...

    def contextChanged(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getActionContext(self, __a0: java.awt.event.MouseEvent) -> docking.ActionContext: ...

    def getClass(self) -> java.lang.Class: ...

    def getComponent(self) -> javax.swing.JComponent: ...

    def getContextType(self) -> java.lang.Class: ...

    def getDefaultWindowPosition(self) -> docking.WindowPosition: ...

    def getHelpInfo(self) -> unicode: ...

    def getHelpLocation(self) -> ghidra.util.HelpLocation: ...

    def getHelpObject(self) -> object: ...

    def getIcon(self) -> javax.swing.Icon: ...

    def getInstanceID(self) -> long: ...

    def getIntraGroupPosition(self) -> docking.WindowPosition: ...

    @staticmethod
    def getMappedName(__a0: unicode, __a1: unicode) -> unicode: ...

    @staticmethod
    def getMappedOwner(__a0: unicode, __a1: unicode) -> unicode: ...

    def getModel(self) -> ghidra.app.plugin.core.strings.ViewStringsTableModel: ...

    def getName(self) -> unicode: ...

    def getOwner(self) -> unicode: ...

    def getProgram(self) -> ghidra.program.model.listing.Program: ...

    def getSelectedData(self) -> ghidra.program.model.listing.Data: ...

    def getSelectedDataList(self, __a0: java.util.function.Predicate) -> List[object]: ...

    def getSelectedDataLocationList(self, __a0: java.util.function.Predicate) -> List[object]: ...

    def getSelectedRowCount(self) -> int: ...

    def getSubTitle(self) -> unicode: ...

    def getTabText(self) -> unicode: ...

    def getTable(self) -> ghidra.util.table.GhidraTable: ...

    def getTitle(self) -> unicode: ...

    def getTool(self) -> docking.Tool: ...

    def getWindowGroup(self) -> unicode: ...

    def getWindowSubMenuName(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def isActive(self) -> bool: ...

    def isFocusedProvider(self) -> bool: ...

    def isInTool(self) -> bool: ...

    def isSnapshot(self) -> bool: ...

    def isTransient(self) -> bool: ...

    def isVisible(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    @staticmethod
    def registerProviderNameOwnerChange(__a0: unicode, __a1: unicode, __a2: unicode, __a3: unicode) -> None: ...

    def removeFromTool(self) -> None: ...

    def requestFocus(self) -> None: ...

    def setHelpLocation(self, __a0: ghidra.util.HelpLocation) -> None: ...

    def setIntraGroupPosition(self, __a0: docking.WindowPosition) -> None: ...

    def setSubTitle(self, __a0: unicode) -> None: ...

    def setTabText(self, __a0: unicode) -> None: ...

    def setTitle(self, __a0: unicode) -> None: ...

    def setVisible(self, __a0: bool) -> None: ...

    def showProgramLocation(self, __a0: ghidra.program.util.ProgramLocation) -> None: ...

    def toFront(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def component(self) -> javax.swing.JComponent: ...

    @property
    def helpLocation(self) -> ghidra.util.HelpLocation: ...

    @helpLocation.setter
    def helpLocation(self, value: ghidra.util.HelpLocation) -> None: ...

    @property
    def model(self) -> ghidra.app.plugin.core.strings.ViewStringsTableModel: ...

    @property
    def program(self) -> ghidra.program.model.listing.Program: ...

    @property
    def selectedData(self) -> ghidra.program.model.listing.Data: ...

    @property
    def selectedRowCount(self) -> int: ...

    @property
    def table(self) -> ghidra.util.table.GhidraTable: ...
