from typing import List
import ghidra.program.util
import ghidra.util.task
import java.lang


class MakeStringsTask(ghidra.program.util.ProgramTask):




    @overload
    def __init__(self, __a0: ghidra.program.model.listing.Program, __a1: ghidra.program.util.string.FoundString, __a2: int, __a3: int, __a4: bool, __a5: bool, __a6: bool, __a7: bool): ...

    @overload
    def __init__(self, __a0: ghidra.program.model.listing.Program, __a1: List[object], __a2: int, __a3: int, __a4: bool, __a5: bool, __a6: bool, __a7: bool): ...



    def addTaskListener(self, __a0: ghidra.util.task.TaskListener) -> None: ...

    def canCancel(self) -> bool: ...

    def cancel(self) -> None: ...

    def doRun(self, __a0: ghidra.util.task.TaskMonitor) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getStatusTextAlignment(self) -> int: ...

    def getStringEvents(self) -> List[object]: ...

    def getTaskTitle(self) -> unicode: ...

    def hasErrors(self) -> bool: ...

    def hasProgress(self) -> bool: ...

    def hashCode(self) -> int: ...

    def isModal(self) -> bool: ...

    def monitoredRun(self, __a0: ghidra.util.task.TaskMonitor) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def run(self, __a0: ghidra.util.task.TaskMonitor) -> None: ...

    def setHasProgress(self, __a0: bool) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def stringEvents(self) -> List[object]: ...
