from typing import List
import java.io
import java.lang


class StringModel(object):




    def __init__(self, __a0: List[int], __a1: List[int], __a2: List[int], __a3: long): ...



    def equals(self, __a0: object) -> bool: ...

    def getBeginTrigramCounts(self) -> List[int]: ...

    def getClass(self) -> java.lang.Class: ...

    def getEndTrigramCounts(self) -> List[int]: ...

    def getTotalNumTrigrams(self) -> long: ...

    def getTrigramCounts(self) -> List[int]: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setTrigramCounts(self, __a0: List[int], __a1: List[int], __a2: List[int], __a3: long) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def writeTrigramModelFile(self, __a0: unicode, __a1: List[object], __a2: unicode, __a3: java.io.File) -> None: ...

    @property
    def beginTrigramCounts(self) -> List[int]: ...

    @property
    def endTrigramCounts(self) -> List[int]: ...

    @property
    def totalNumTrigrams(self) -> long: ...

    @property
    def trigramCounts(self) -> List[int]: ...
