import ghidra.app.plugin.core.searchmem
import java.lang
import javax.swing


class SearchFormat(object):








    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getName(self) -> unicode: ...

    def getOptionsPanel(self) -> javax.swing.JPanel: ...

    def getSearchData(self, __a0: unicode) -> ghidra.app.plugin.core.searchmem.SearchData: ...

    def getToolTip(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setEndieness(self, __a0: bool) -> None: ...

    def supportsBackwardsSearch(self) -> bool: ...

    def toString(self) -> unicode: ...

    def usesEndieness(self) -> bool: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def endieness(self) -> None: ...  # No getter available.

    @endieness.setter
    def endieness(self, value: bool) -> None: ...

    @property
    def name(self) -> unicode: ...

    @property
    def optionsPanel(self) -> javax.swing.JPanel: ...

    @property
    def toolTip(self) -> unicode: ...
