import java.lang


class Token(object):




    def __init__(self, __a0: unicode, __a1: int, __a2: bool, __a3: int): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getIndex(self) -> int: ...

    def getName(self) -> unicode: ...

    def getSize(self) -> int: ...

    def hashCode(self) -> int: ...

    def isBigEndian(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def bigEndian(self) -> bool: ...

    @property
    def index(self) -> int: ...

    @property
    def name(self) -> unicode: ...

    @property
    def size(self) -> int: ...
