import ghidra.bitpatterns.info
import java.lang
import org.jdom


class ContextRegisterInfo(object):




    @overload
    def __init__(self): ...

    @overload
    def __init__(self, __a0: unicode): ...



    def equals(self, __a0: object) -> bool: ...

    @staticmethod
    def fromXml(__a0: org.jdom.Element) -> ghidra.bitpatterns.info.ContextRegisterInfo: ...

    def getClass(self) -> java.lang.Class: ...

    def getContextRegister(self) -> unicode: ...

    def getValue(self) -> long: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setContextRegister(self, __a0: unicode) -> None: ...

    def setValue(self, __a0: long) -> None: ...

    def toString(self) -> unicode: ...

    def toXml(self) -> org.jdom.Element: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def contextRegister(self) -> unicode: ...

    @contextRegister.setter
    def contextRegister(self, value: unicode) -> None: ...

    @property
    def value(self) -> long: ...

    @value.setter
    def value(self, value: long) -> None: ...
