from typing import List
import java.lang
import java.util


class ContextRegisterFilter(object):




    def __init__(self): ...



    def addRegAndValueToFilter(self, __a0: unicode, __a1: long) -> None: ...

    def allows(self, __a0: List[object]) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getCompactString(self) -> unicode: ...

    def getValueMap(self) -> java.util.Map: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def compactString(self) -> unicode: ...

    @property
    def valueMap(self) -> java.util.Map: ...
