from typing import List
import ghidra.bitpatterns.info
import java.io
import java.lang
import org.jdom


class FileBitPatternInfo(object):




    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    @staticmethod
    def fromXml(__a0: org.jdom.Element) -> ghidra.bitpatterns.info.FileBitPatternInfo: ...

    @staticmethod
    def fromXmlFile(__a0: java.io.File) -> ghidra.bitpatterns.info.FileBitPatternInfo: ...

    def getClass(self) -> java.lang.Class: ...

    def getFuncBitPatternInfo(self) -> List[object]: ...

    def getGhidraURL(self) -> unicode: ...

    def getLanguageID(self) -> unicode: ...

    def getNumFirstBytes(self) -> int: ...

    def getNumFirstInstructions(self) -> int: ...

    def getNumPreBytes(self) -> int: ...

    def getNumPreInstructions(self) -> int: ...

    def getNumReturnBytes(self) -> int: ...

    def getNumReturnInstructions(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setFuncBitPatternInfo(self, __a0: List[object]) -> None: ...

    def setGhidraURL(self, __a0: unicode) -> None: ...

    def setLanguageID(self, __a0: unicode) -> None: ...

    def setNumFirstBytes(self, __a0: int) -> None: ...

    def setNumFirstInstructions(self, __a0: int) -> None: ...

    def setNumPreBytes(self, __a0: int) -> None: ...

    def setNumPreInstructions(self, __a0: int) -> None: ...

    def setNumReturnBytes(self, __a0: int) -> None: ...

    def setNumReturnInstructions(self, __a0: int) -> None: ...

    def toString(self) -> unicode: ...

    def toXml(self) -> org.jdom.Element: ...

    def toXmlFile(self, __a0: java.io.File) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def funcBitPatternInfo(self) -> List[object]: ...

    @funcBitPatternInfo.setter
    def funcBitPatternInfo(self, value: List[object]) -> None: ...

    @property
    def ghidraURL(self) -> unicode: ...

    @ghidraURL.setter
    def ghidraURL(self, value: unicode) -> None: ...

    @property
    def languageID(self) -> unicode: ...

    @languageID.setter
    def languageID(self, value: unicode) -> None: ...

    @property
    def numFirstBytes(self) -> int: ...

    @numFirstBytes.setter
    def numFirstBytes(self, value: int) -> None: ...

    @property
    def numFirstInstructions(self) -> int: ...

    @numFirstInstructions.setter
    def numFirstInstructions(self, value: int) -> None: ...

    @property
    def numPreBytes(self) -> int: ...

    @numPreBytes.setter
    def numPreBytes(self, value: int) -> None: ...

    @property
    def numPreInstructions(self) -> int: ...

    @numPreInstructions.setter
    def numPreInstructions(self, value: int) -> None: ...

    @property
    def numReturnBytes(self) -> int: ...

    @numReturnBytes.setter
    def numReturnBytes(self, value: int) -> None: ...

    @property
    def numReturnInstructions(self) -> int: ...

    @numReturnInstructions.setter
    def numReturnInstructions(self, value: int) -> None: ...
