from typing import List
import ghidra.bitpatterns.info
import java.lang
import org.jdom


class FunctionBitPatternInfo(object):




    @overload
    def __init__(self): ...

    @overload
    def __init__(self, __a0: ghidra.program.model.listing.Program, __a1: ghidra.program.model.listing.Function, __a2: ghidra.bitpatterns.info.DataGatheringParams): ...



    def equals(self, __a0: object) -> bool: ...

    @staticmethod
    def fromXml(__a0: org.jdom.Element) -> ghidra.bitpatterns.info.FunctionBitPatternInfo: ...

    def getAddress(self) -> unicode: ...

    def getClass(self) -> java.lang.Class: ...

    def getContextRegisters(self) -> List[object]: ...

    def getFirstBytes(self) -> unicode: ...

    def getFirstInst(self) -> ghidra.bitpatterns.info.InstructionSequence: ...

    def getPreBytes(self) -> unicode: ...

    def getPreInst(self) -> ghidra.bitpatterns.info.InstructionSequence: ...

    def getReturnBytes(self) -> List[object]: ...

    def getReturnInst(self) -> List[object]: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setAddress(self, __a0: unicode) -> None: ...

    def setContextRegisters(self, __a0: List[object]) -> None: ...

    def setFirstBytes(self, __a0: unicode) -> None: ...

    def setFirstInst(self, __a0: ghidra.bitpatterns.info.InstructionSequence) -> None: ...

    def setPreBytes(self, __a0: unicode) -> None: ...

    def setPreInst(self, __a0: ghidra.bitpatterns.info.InstructionSequence) -> None: ...

    def setReturnBytes(self, __a0: List[object]) -> None: ...

    def setReturnInst(self, __a0: List[object]) -> None: ...

    def toString(self) -> unicode: ...

    def toXml(self) -> org.jdom.Element: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def address(self) -> unicode: ...

    @address.setter
    def address(self, value: unicode) -> None: ...

    @property
    def contextRegisters(self) -> List[object]: ...

    @contextRegisters.setter
    def contextRegisters(self, value: List[object]) -> None: ...

    @property
    def firstBytes(self) -> unicode: ...

    @firstBytes.setter
    def firstBytes(self, value: unicode) -> None: ...

    @property
    def firstInst(self) -> ghidra.bitpatterns.info.InstructionSequence: ...

    @firstInst.setter
    def firstInst(self, value: ghidra.bitpatterns.info.InstructionSequence) -> None: ...

    @property
    def preBytes(self) -> unicode: ...

    @preBytes.setter
    def preBytes(self, value: unicode) -> None: ...

    @property
    def preInst(self) -> ghidra.bitpatterns.info.InstructionSequence: ...

    @preInst.setter
    def preInst(self, value: ghidra.bitpatterns.info.InstructionSequence) -> None: ...

    @property
    def returnBytes(self) -> List[object]: ...

    @returnBytes.setter
    def returnBytes(self, value: List[object]) -> None: ...

    @property
    def returnInst(self) -> List[object]: ...

    @returnInst.setter
    def returnInst(self, value: List[object]) -> None: ...
