from typing import List
import ghidra.bitpatterns.info
import java.lang
import org.jdom


class InstructionSequence(object):




    @overload
    def __init__(self): ...

    @overload
    def __init__(self, __a0: int): ...



    def equals(self, __a0: object) -> bool: ...

    @staticmethod
    def fromXml(__a0: org.jdom.Element) -> ghidra.bitpatterns.info.InstructionSequence: ...

    def getClass(self) -> java.lang.Class: ...

    def getCommaSeparatedOperands(self) -> List[unicode]: ...

    def getCompleteDisassembly(self, __a0: bool) -> unicode: ...

    def getDisassembly(self, __a0: int, __a1: bool) -> unicode: ...

    @staticmethod
    def getInstSeqs(__a0: ghidra.bitpatterns.info.FileBitPatternInfoReader, __a1: ghidra.bitpatterns.info.PatternType, __a2: ghidra.bitpatterns.info.ContextRegisterFilter) -> List[object]: ...

    def getInstructions(self) -> List[unicode]: ...

    def getSizes(self) -> List[int]: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setCommaSeparatedOperands(self, __a0: List[unicode]) -> None: ...

    def setInstructions(self, __a0: List[unicode]) -> None: ...

    def setSizes(self, __a0: List[int]) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def toXml(self) -> org.jdom.Element: ...

    @overload
    def toXml(self, __a0: unicode) -> org.jdom.Element: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def commaSeparatedOperands(self) -> List[unicode]: ...

    @commaSeparatedOperands.setter
    def commaSeparatedOperands(self, value: List[unicode]) -> None: ...

    @property
    def instructions(self) -> List[unicode]: ...

    @instructions.setter
    def instructions(self, value: List[unicode]) -> None: ...

    @property
    def sizes(self) -> List[int]: ...

    @sizes.setter
    def sizes(self, value: List[int]) -> None: ...
