import ghidra.feature.vt.api.main
import ghidra.program.model.listing
import java.lang


class FunctionAssociationContext(object):








    def canCreateMatch(self) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getExistingMatch(self) -> ghidra.feature.vt.api.main.VTMatch: ...

    def getSelectedSourceFunction(self) -> ghidra.program.model.listing.Function: ...

    def getSelectionDestinationFunction(self) -> ghidra.program.model.listing.Function: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def existingMatch(self) -> ghidra.feature.vt.api.main.VTMatch: ...

    @property
    def selectedSourceFunction(self) -> ghidra.program.model.listing.Function: ...

    @property
    def selectionDestinationFunction(self) -> ghidra.program.model.listing.Function: ...
