import docking
import ghidra.feature.vt.api.main
import ghidra.feature.vt.gui.provider.functionassociation
import ghidra.framework.plugintool
import ghidra.program.model.listing
import java.awt
import java.awt.event
import java.lang


class VTFunctionAssociationContext(docking.ActionContext, ghidra.feature.vt.gui.provider.functionassociation.FunctionAssociationContext):




    def __init__(self, __a0: ghidra.framework.plugintool.PluginTool, __a1: ghidra.program.model.listing.Function, __a2: ghidra.program.model.listing.Function, __a3: ghidra.feature.vt.api.main.VTMatch): ...



    def canCreateMatch(self) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getComponentProvider(self) -> docking.ComponentProvider: ...

    def getContextObject(self) -> object: ...

    def getExistingMatch(self) -> ghidra.feature.vt.api.main.VTMatch: ...

    def getGlobalContext(self) -> docking.ActionContext: ...

    def getMouseEvent(self) -> java.awt.event.MouseEvent: ...

    def getSelectedSourceFunction(self) -> ghidra.program.model.listing.Function: ...

    def getSelectionDestinationFunction(self) -> ghidra.program.model.listing.Function: ...

    def getSourceComponent(self) -> java.awt.Component: ...

    def getSourceObject(self) -> object: ...

    def getTool(self) -> ghidra.framework.plugintool.PluginTool: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setContextObject(self, __a0: object) -> docking.ActionContext: ...

    def setMouseEvent(self, __a0: java.awt.event.MouseEvent) -> docking.ActionContext: ...

    def setSourceObject(self, __a0: object) -> docking.ActionContext: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def existingMatch(self) -> ghidra.feature.vt.api.main.VTMatch: ...

    @property
    def selectedSourceFunction(self) -> ghidra.program.model.listing.Function: ...

    @property
    def selectionDestinationFunction(self) -> ghidra.program.model.listing.Function: ...

    @property
    def tool(self) -> ghidra.framework.plugintool.PluginTool: ...
