import docking
import ghidra.app.nav
import ghidra.app.util.viewer.util
import ghidra.feature.vt.api.main
import ghidra.feature.vt.gui.duallisting
import ghidra.feature.vt.gui.provider.functionassociation
import ghidra.program.model.address
import ghidra.program.model.listing
import ghidra.program.util
import java.awt
import java.awt.event
import java.lang


class VTFunctionAssociationCompareContext(ghidra.feature.vt.gui.duallisting.VTListingContext, ghidra.feature.vt.gui.provider.functionassociation.FunctionAssociationContext):




    def __init__(self, __a0: docking.ComponentProvider, __a1: ghidra.app.nav.Navigatable, __a2: ghidra.framework.plugintool.PluginTool, __a3: ghidra.program.model.listing.Function, __a4: ghidra.program.model.listing.Function, __a5: ghidra.feature.vt.api.main.VTMatch): ...



    def canCreateMatch(self) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getAddress(self) -> ghidra.program.model.address.Address: ...

    def getClass(self) -> java.lang.Class: ...

    def getCodeComparisonPanel(self) -> ghidra.app.util.viewer.util.CodeComparisonPanel: ...

    def getCodeUnit(self) -> ghidra.program.model.listing.CodeUnit: ...

    def getComponentProvider(self) -> docking.ComponentProvider: ...

    def getContextObject(self) -> object: ...

    def getExistingMatch(self) -> ghidra.feature.vt.api.main.VTMatch: ...

    def getGlobalContext(self) -> docking.ActionContext: ...

    def getHighlight(self) -> ghidra.program.util.ProgramSelection: ...

    def getLocation(self) -> ghidra.program.util.ProgramLocation: ...

    def getMouseEvent(self) -> java.awt.event.MouseEvent: ...

    def getNavigatable(self) -> ghidra.app.nav.Navigatable: ...

    def getProgram(self) -> ghidra.program.model.listing.Program: ...

    def getSelectedSourceFunction(self) -> ghidra.program.model.listing.Function: ...

    def getSelection(self) -> ghidra.program.util.ProgramSelection: ...

    def getSelectionDestinationFunction(self) -> ghidra.program.model.listing.Function: ...

    def getSourceComponent(self) -> java.awt.Component: ...

    def getSourceObject(self) -> object: ...

    def hasHighlight(self) -> bool: ...

    def hasSelection(self) -> bool: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setCodeComparisonPanel(self, __a0: ghidra.app.util.viewer.util.CodeComparisonPanel) -> None: ...

    def setContextObject(self, __a0: object) -> docking.ActionContext: ...

    def setMouseEvent(self, __a0: java.awt.event.MouseEvent) -> docking.ActionContext: ...

    def setSourceObject(self, __a0: object) -> docking.ActionContext: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def existingMatch(self) -> ghidra.feature.vt.api.main.VTMatch: ...

    @property
    def selectedSourceFunction(self) -> ghidra.program.model.listing.Function: ...

    @property
    def selectionDestinationFunction(self) -> ghidra.program.model.listing.Function: ...
