import ghidra.app.util.bin.format.pdb
import java.lang


class DefaultPdbUniversalMember(ghidra.app.util.bin.format.pdb.PdbMember):








    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getComment(self) -> unicode: ...

    def getDataTypeName(self) -> unicode: ...

    def getName(self) -> unicode: ...

    def getOffset(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def dataTypeName(self) -> unicode: ...
