import java.awt
import java.lang
import javax.swing


class CenterVerticalIcon(object, javax.swing.Icon):




    def __init__(self, __a0: javax.swing.Icon, __a1: int): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getIconHeight(self) -> int: ...

    def getIconWidth(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def paintIcon(self, __a0: java.awt.Component, __a1: java.awt.Graphics, __a2: int, __a3: int) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def iconHeight(self) -> int: ...

    @property
    def iconWidth(self) -> int: ...
