import ghidra.graph.job
import ghidra.util.task
import java.lang
import org.jdesktop.animation.timing


class CenterAnimationJob(ghidra.graph.job.AbstractAnimatorJob):




    def __init__(self, __a0: org.jungrapht.visualization.VisualizationViewer, __a1: java.awt.geom.Point2D, __a2: java.awt.geom.Point2D): ...



    def canShortcut(self) -> bool: ...

    def createAnimator(self) -> org.jdesktop.animation.timing.Animator: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def execute(self, __a0: ghidra.graph.job.GraphJobListener) -> None: ...

    def finished(self) -> None: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def isFinished(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setBusyListener(self, __a0: ghidra.util.task.BusyListener) -> None: ...

    def setPercentComplete(self, __a0: float) -> None: ...

    def shortcut(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def percentComplete(self) -> None: ...  # No getter available.

    @percentComplete.setter
    def percentComplete(self, value: float) -> None: ...
