from typing import List
import java.io
import java.lang


class iOS_AesCrypto(object):
    CRYPTO_ALGORITHM: unicode = u'AES'
    CRYPTO_TRANSFORMATION_CBC: unicode = u'AES/CBC/NoPadding'



    def __init__(self, __a0: List[int], __a1: List[int]): ...



    @overload
    def decrypt(self, __a0: List[int]) -> List[int]: ...

    @overload
    def decrypt(self, __a0: java.io.InputStream) -> java.io.InputStream: ...

    def encrypt(self, __a0: List[int]) -> List[int]: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    def update(self, __a0: List[int]) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
