import ghidra.file.formats.bplist
import ghidra.program.model.data
import ghidra.program.model.listing
import ghidra.util.task
import java.lang


class NSNumber(ghidra.file.formats.bplist.NSObject):




    @overload
    def __init__(self, __a0: long): ...

    @overload
    def __init__(self, __a0: int): ...

    @overload
    def __init__(self, __a0: int): ...

    @overload
    def __init__(self, __a0: int): ...

    @overload
    def __init__(self, __a0: float): ...

    @overload
    def __init__(self, __a0: bool): ...



    def booleanValue(self) -> bool: ...

    def doubleValue(self) -> float: ...

    def equals(self, __a0: object) -> bool: ...

    def floatValue(self) -> float: ...

    def getClass(self) -> java.lang.Class: ...

    def getNumberType(self) -> ghidra.file.formats.bplist.NSNumberTypes: ...

    def getType(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def intValue(self) -> int: ...

    def longValue(self) -> long: ...

    def markup(self, __a0: ghidra.program.model.listing.Data, __a1: ghidra.program.model.listing.Program, __a2: ghidra.util.task.TaskMonitor) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def numberType(self) -> ghidra.file.formats.bplist.NSNumberTypes: ...

    @property
    def type(self) -> unicode: ...
