from typing import List
import generic.jar
import ghidra.framework
import java.io
import java.lang
import java.util
import utility.application


class GhidraServerApplicationLayout(utility.application.ApplicationLayout):




    def __init__(self): ...



    def createUserDirs(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getApplicationInstallationDir(self) -> generic.jar.ResourceFile: ...

    def getApplicationProperties(self) -> ghidra.framework.ApplicationProperties: ...

    def getApplicationRootDirs(self) -> java.util.Collection: ...

    def getClass(self) -> java.lang.Class: ...

    def getExtensionArchiveDir(self) -> generic.jar.ResourceFile: ...

    def getExtensionInstallationDirs(self) -> List[object]: ...

    def getModules(self) -> java.util.Map: ...

    def getPatchDir(self) -> generic.jar.ResourceFile: ...

    def getUserCacheDir(self) -> java.io.File: ...

    def getUserSettingsDir(self) -> java.io.File: ...

    def getUserTempDir(self) -> java.io.File: ...

    def hashCode(self) -> int: ...

    def inSingleJarMode(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
