from typing import Iterator
from typing import List
import java.lang
import java.util
import java.util.function
import java.util.stream


class QueueStub(object, java.util.Queue):
    """
    A do-nothing, stubbed version of the Queue interface.
    """





    def __init__(self): ...

    def __iter__(self): ...

    def add(self, __a0: object) -> bool: ...

    def addAll(self, c: java.util.Collection) -> bool: ...

    def clear(self) -> None: ...

    def contains(self, o: object) -> bool: ...

    def containsAll(self, c: java.util.Collection) -> bool: ...

    def element(self) -> E: ...

    def equals(self, __a0: object) -> bool: ...

    def forEach(self, __a0: java.util.function.Consumer) -> None: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def isEmpty(self) -> bool: ...

    def iterator(self) -> Iterator[E]: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def offer(self, __a0: object) -> bool: ...

    def parallelStream(self) -> java.util.stream.Stream: ...

    def peek(self) -> E: ...

    def poll(self) -> E: ...

    @overload
    def remove(self) -> E: ...

    @overload
    def remove(self, o: object) -> bool: ...

    def removeAll(self, c: java.util.Collection) -> bool: ...

    def removeIf(self, __a0: java.util.function.Predicate) -> bool: ...

    def retainAll(self, c: java.util.Collection) -> bool: ...

    def size(self) -> int: ...

    def spliterator(self) -> java.util.Spliterator: ...

    def stream(self) -> java.util.stream.Stream: ...

    @overload
    def toArray(self) -> List[object]: ...

    @overload
    def toArray(self, a: List[object]) -> List[object]: ...

    @overload
    def toArray(self, __a0: java.util.function.IntFunction) -> List[object]: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def empty(self) -> bool: ...
