import ghidra.feature.fid.service
import java.lang


class DefaultFidPopulateResultReporter(object, ghidra.feature.fid.service.FidPopulateResultReporter):




    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def report(self, __a0: ghidra.feature.fid.service.FidPopulateResult) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
