import ghidra.feature.fid.db
import ghidra.feature.fid.plugin
import java.lang


class FidMatchScore(object):








    def equals(self, __a0: object) -> bool: ...

    def getChildFunctionCodeUnitScore(self) -> float: ...

    def getClass(self) -> java.lang.Class: ...

    def getFunctionRecord(self) -> ghidra.feature.fid.db.FunctionRecord: ...

    def getOverallScore(self) -> float: ...

    def getParentFunctionCodeUnitScore(self) -> float: ...

    def getPrimaryFunctionCodeUnitScore(self) -> float: ...

    def getPrimaryFunctionMatchMode(self) -> ghidra.feature.fid.plugin.HashLookupListMode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def childFunctionCodeUnitScore(self) -> float: ...

    @property
    def functionRecord(self) -> ghidra.feature.fid.db.FunctionRecord: ...

    @property
    def overallScore(self) -> float: ...

    @property
    def parentFunctionCodeUnitScore(self) -> float: ...

    @property
    def primaryFunctionCodeUnitScore(self) -> float: ...

    @property
    def primaryFunctionMatchMode(self) -> ghidra.feature.fid.plugin.HashLookupListMode: ...
