import ghidra.feature.fid.hash
import ghidra.program.model.address
import java.lang
import java.util


class HashFamily(object):








    def equals(self, __a0: object) -> bool: ...

    def getAddress(self) -> ghidra.program.model.address.Address: ...

    def getChildren(self) -> java.util.Collection: ...

    def getClass(self) -> java.lang.Class: ...

    def getHash(self) -> ghidra.feature.fid.hash.FidHashQuad: ...

    def getParents(self) -> java.util.Collection: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def address(self) -> ghidra.program.model.address.Address: ...

    @property
    def children(self) -> java.util.Collection: ...

    @property
    def hash(self) -> ghidra.feature.fid.hash.FidHashQuad: ...

    @property
    def parents(self) -> java.util.Collection: ...
