import ghidra.framework.model
import ghidra.program.model.address
import java.lang


class Location(object):




    def __init__(self, __a0: ghidra.framework.model.DomainFile, __a1: unicode, __a2: ghidra.program.model.address.Address): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDomainFile(self) -> ghidra.framework.model.DomainFile: ...

    def getFunctionEntryPoint(self) -> ghidra.program.model.address.Address: ...

    def getFunctionName(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def domainFile(self) -> ghidra.framework.model.DomainFile: ...

    @property
    def functionEntryPoint(self) -> ghidra.program.model.address.Address: ...

    @property
    def functionName(self) -> unicode: ...
