from typing import List
import ghidra.program.model.listing
import ghidra.program.util
import java.lang
import java.util
import javax.swing
import javax.swing.tree


class ProgramNode(javax.swing.tree.DefaultMutableTreeNode):








    def add(self, __a0: javax.swing.tree.MutableTreeNode) -> None: ...

    def breadthFirstEnumeration(self) -> java.util.Enumeration: ...

    def children(self) -> java.util.Enumeration: ...

    def clone(self) -> object: ...

    def depthFirstEnumeration(self) -> java.util.Enumeration: ...

    def equals(self, __a0: object) -> bool: ...

    def getAllowsChildren(self) -> bool: ...

    def getChildAfter(self, __a0: javax.swing.tree.TreeNode) -> javax.swing.tree.TreeNode: ...

    def getChildAt(self, __a0: int) -> javax.swing.tree.TreeNode: ...

    def getChildBefore(self, __a0: javax.swing.tree.TreeNode) -> javax.swing.tree.TreeNode: ...

    def getChildCount(self) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def getDepth(self) -> int: ...

    def getFirstChild(self) -> javax.swing.tree.TreeNode: ...

    def getFirstLeaf(self) -> javax.swing.tree.DefaultMutableTreeNode: ...

    def getFragment(self) -> ghidra.program.model.listing.ProgramFragment: ...

    def getGroup(self) -> ghidra.program.model.listing.Group: ...

    def getGroupPath(self) -> ghidra.program.util.GroupPath: ...

    def getIndex(self, __a0: javax.swing.tree.TreeNode) -> int: ...

    def getLastChild(self) -> javax.swing.tree.TreeNode: ...

    def getLastLeaf(self) -> javax.swing.tree.DefaultMutableTreeNode: ...

    def getLeafCount(self) -> int: ...

    def getLevel(self) -> int: ...

    def getModule(self) -> ghidra.program.model.listing.ProgramModule: ...

    def getName(self) -> unicode: ...

    def getNextLeaf(self) -> javax.swing.tree.DefaultMutableTreeNode: ...

    def getNextNode(self) -> javax.swing.tree.DefaultMutableTreeNode: ...

    def getNextSibling(self) -> javax.swing.tree.DefaultMutableTreeNode: ...

    def getParent(self) -> javax.swing.tree.TreeNode: ...

    def getPath(self) -> List[javax.swing.tree.TreeNode]: ...

    def getPreviousLeaf(self) -> javax.swing.tree.DefaultMutableTreeNode: ...

    def getPreviousNode(self) -> javax.swing.tree.DefaultMutableTreeNode: ...

    def getPreviousSibling(self) -> javax.swing.tree.DefaultMutableTreeNode: ...

    def getProgram(self) -> ghidra.program.model.listing.Program: ...

    def getRoot(self) -> javax.swing.tree.TreeNode: ...

    def getSharedAncestor(self, __a0: javax.swing.tree.DefaultMutableTreeNode) -> javax.swing.tree.TreeNode: ...

    def getSiblingCount(self) -> int: ...

    def getTree(self) -> javax.swing.JTree: ...

    def getUserObject(self) -> object: ...

    def getUserObjectPath(self) -> List[object]: ...

    def hashCode(self) -> int: ...

    def insert(self, __a0: javax.swing.tree.MutableTreeNode, __a1: int) -> None: ...

    def isFragment(self) -> bool: ...

    def isInView(self) -> bool: ...

    def isLeaf(self) -> bool: ...

    def isModule(self) -> bool: ...

    def isNodeAncestor(self, __a0: javax.swing.tree.TreeNode) -> bool: ...

    def isNodeChild(self, __a0: javax.swing.tree.TreeNode) -> bool: ...

    def isNodeDescendant(self, __a0: javax.swing.tree.DefaultMutableTreeNode) -> bool: ...

    def isNodeRelated(self, __a0: javax.swing.tree.DefaultMutableTreeNode) -> bool: ...

    def isNodeSibling(self, __a0: javax.swing.tree.TreeNode) -> bool: ...

    def isRoot(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def pathFromAncestorEnumeration(self, __a0: javax.swing.tree.TreeNode) -> java.util.Enumeration: ...

    def postorderEnumeration(self) -> java.util.Enumeration: ...

    def preorderEnumeration(self) -> java.util.Enumeration: ...

    @overload
    def remove(self, __a0: int) -> None: ...

    @overload
    def remove(self, __a0: javax.swing.tree.MutableTreeNode) -> None: ...

    def removeAllChildren(self) -> None: ...

    def removeFromParent(self) -> None: ...

    def setAllowsChildren(self, __a0: bool) -> None: ...

    def setParent(self, __a0: javax.swing.tree.MutableTreeNode) -> None: ...

    def setUserObject(self, __a0: object) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def allowsChildren(self) -> bool: ...

    @allowsChildren.setter
    def allowsChildren(self, value: bool) -> None: ...

    @property
    def fragment(self) -> bool: ...

    @property
    def group(self) -> ghidra.program.model.listing.Group: ...

    @property
    def groupPath(self) -> ghidra.program.util.GroupPath: ...

    @property
    def inView(self) -> bool: ...

    @property
    def leaf(self) -> bool: ...

    @property
    def module(self) -> bool: ...

    @property
    def name(self) -> unicode: ...

    @property
    def program(self) -> ghidra.program.model.listing.Program: ...

    @property
    def tree(self) -> javax.swing.JTree: ...
