import ghidra.util
import java.lang


class JavaSourceFile(object):




    def __init__(self, filename: unicode): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getImportSectionStartLineNumber(self) -> int: ...

    def getJavaStatementStartingAtLine(self, firstUseLineNumber: int) -> unicode: ...

    def getLine(self, oneBasedLineNumber: int) -> ghidra.util.JavaSourceLine: ...

    def getLineContaintingStatementStart(self, lineNumber: int) -> ghidra.util.JavaSourceLine: ...

    def getLineNumberAfterStatementAtLine(self, lineNumber: int) -> int: ...

    def getOriginalSourceFileCopy(self) -> ghidra.util.JavaSourceFile: ...

    def hasChanges(self) -> bool: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def removeJavaStatement(self, lineNumber: int) -> None: ...

    def save(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def importSectionStartLineNumber(self) -> int: ...

    @property
    def originalSourceFileCopy(self) -> ghidra.util.JavaSourceFile: ...
