import ghidra.util
import java.awt
import java.lang


class SaveablePoint(ghidra.util.PrivateSaveable):




    @overload
    def __init__(self): ...

    @overload
    def __init__(self, point: java.awt.Point): ...



    def equals(self, obj: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getObjectStorageFields(self) -> java.lang.Class: ...

    def getPoint(self) -> java.awt.Point: ...

    def getSchemaVersion(self) -> int: ...

    def hashCode(self) -> int: ...

    def isPrivate(self) -> bool: ...

    def isUpgradeable(self, oldSchemaVersion: int) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def restore(self, objStorage: ghidra.util.ObjectStorage) -> None: ...

    def save(self, objStorage: ghidra.util.ObjectStorage) -> None: ...

    def toString(self) -> unicode: ...

    def upgrade(self, oldObjStorage: ghidra.util.ObjectStorage, oldSchemaVersion: int, currentObjStorage: ghidra.util.ObjectStorage) -> bool: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def objectStorageFields(self) -> List[java.lang.Class]: ...

    @property
    def point(self) -> java.awt.Point: ...

    @property
    def schemaVersion(self) -> int: ...
