from typing import List
import java.lang


class ExternalPath(object):




    def __init__(self, strings: List[unicode]): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getLibraryName(self) -> unicode: ...

    def getName(self) -> unicode: ...

    def getPathElements(self) -> List[unicode]: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def libraryName(self) -> unicode: ...

    @property
    def name(self) -> unicode: ...

    @property
    def pathElements(self) -> List[unicode]: ...
