import ghidra.app.plugin.core.compositeeditor
import ghidra.app.plugin.core.stackeditor
import ghidra.program.model.listing
import java.lang


class StackEditorManager(object, ghidra.app.plugin.core.compositeeditor.EditorListener):




    def __init__(self, __a0: ghidra.app.plugin.core.stackeditor.StackEditorManagerPlugin): ...



    def closed(self, __a0: ghidra.app.plugin.core.compositeeditor.EditorProvider) -> None: ...

    def dispose(self) -> None: ...

    def edit(self, __a0: ghidra.program.model.listing.Function) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getProvider(self, __a0: ghidra.program.model.listing.Function) -> ghidra.app.plugin.core.stackeditor.StackEditorProvider: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
