from typing import List
import ghidra.program.model.address
import java.lang


class ByteEditInfo(object):




    def __init__(self, __a0: ghidra.program.model.address.Address, __a1: long, __a2: List[int], __a3: List[int]): ...



    def equals(self, __a0: object) -> bool: ...

    def getBlockAddress(self) -> ghidra.program.model.address.Address: ...

    def getClass(self) -> java.lang.Class: ...

    def getNewValue(self) -> List[int]: ...

    def getOffset(self) -> long: ...

    def getOldValue(self) -> List[int]: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def blockAddress(self) -> ghidra.program.model.address.Address: ...

    @property
    def newValue(self) -> List[int]: ...

    @property
    def offset(self) -> long: ...

    @property
    def oldValue(self) -> List[int]: ...
