import ghidra.app.plugin.core.format
import java.lang


class ByteBlockInfo(object):




    @overload
    def __init__(self, __a0: ghidra.app.plugin.core.format.ByteBlock, __a1: long): ...

    @overload
    def __init__(self, __a0: ghidra.app.plugin.core.format.ByteBlock, __a1: long, __a2: int): ...



    def equals(self, __a0: object) -> bool: ...

    def getBlock(self) -> ghidra.app.plugin.core.format.ByteBlock: ...

    def getClass(self) -> java.lang.Class: ...

    def getColumn(self) -> int: ...

    def getOffset(self) -> long: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def block(self) -> ghidra.app.plugin.core.format.ByteBlock: ...

    @property
    def column(self) -> int: ...

    @property
    def offset(self) -> long: ...
