import ghidra.app.plugin.core.format
import java.lang


class ByteBlockRange(object):




    def __init__(self, __a0: ghidra.app.plugin.core.format.ByteBlock, __a1: long, __a2: long): ...



    def equals(self, __a0: object) -> bool: ...

    def getByteBlock(self) -> ghidra.app.plugin.core.format.ByteBlock: ...

    def getClass(self) -> java.lang.Class: ...

    def getEndIndex(self) -> long: ...

    def getStartIndex(self) -> long: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def byteBlock(self) -> ghidra.app.plugin.core.format.ByteBlock: ...

    @property
    def endIndex(self) -> long: ...

    @property
    def startIndex(self) -> long: ...
