import docking.widgets
import docking.widgets.fieldpanel.support
import java.lang


class FieldBasedSearchLocation(docking.widgets.SearchLocation):




    def __init__(self, __a0: docking.widgets.fieldpanel.support.FieldLocation, __a1: int, __a2: int, __a3: unicode, __a4: bool): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getCursorPosition(self) -> docking.widgets.CursorPosition: ...

    def getEndIndexInclusive(self) -> int: ...

    def getFieldLocation(self) -> docking.widgets.fieldpanel.support.FieldLocation: ...

    def getMatchLength(self) -> int: ...

    def getSearchText(self) -> unicode: ...

    def getStartIndexInclusive(self) -> int: ...

    def hashCode(self) -> int: ...

    def isForwardDirection(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def cursorPosition(self) -> docking.widgets.CursorPosition: ...

    @property
    def fieldLocation(self) -> docking.widgets.fieldpanel.support.FieldLocation: ...
