import edu.uci.ics.jung.visualization
import edu.uci.ics.jung.visualization.control
import ghidra.graph.viewer
import ghidra.graph.viewer.event.mouse
import java.awt
import java.awt.event
import java.lang


class VisualGraphScalingGraphMousePlugin(edu.uci.ics.jung.visualization.control.ScalingGraphMousePlugin, ghidra.graph.viewer.event.mouse.VisualGraphMousePlugin):
    """
    Overridden implementation that allows us to change scaling behavior through options.  This
     class works on the opposite modifier setup as FunctionGraphScrollWheelPanningPlugin.
    """





    def __init__(self): ...



    def checkModifiers(self, e: java.awt.event.MouseEvent) -> bool: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getCursor(self) -> java.awt.Cursor: ...

    def getGraphViewer(self, __a0: java.awt.event.MouseEvent) -> ghidra.graph.viewer.GraphViewer: ...

    def getIn(self) -> float: ...

    def getModifiers(self) -> int: ...

    def getOut(self) -> float: ...

    def getSatelliteGraphViewer(self, __a0: java.awt.event.MouseEvent) -> ghidra.graph.viewer.SatelliteGraphViewer: ...

    def getScaler(self) -> edu.uci.ics.jung.visualization.control.ScalingControl: ...

    @overload
    def getViewUpdater(self, __a0: ghidra.graph.viewer.GraphViewer) -> ghidra.graph.viewer.VisualGraphViewUpdater: ...

    @overload
    def getViewUpdater(self, __a0: java.awt.event.MouseEvent) -> ghidra.graph.viewer.VisualGraphViewUpdater: ...

    def getViewer(self, __a0: java.awt.event.MouseEvent) -> edu.uci.ics.jung.visualization.VisualizationViewer: ...

    def hashCode(self) -> int: ...

    def mouseWheelMoved(self, __a0: java.awt.event.MouseWheelEvent) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setCursor(self, __a0: java.awt.Cursor) -> None: ...

    def setIn(self, __a0: float) -> None: ...

    def setModifiers(self, __a0: int) -> None: ...

    def setOut(self, __a0: float) -> None: ...

    def setScaler(self, __a0: edu.uci.ics.jung.visualization.control.ScalingControl) -> None: ...

    def setZoomAtMouse(self, __a0: bool) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...
