from typing import List
import ghidra.framework.plugintool.util
import java.lang
import java.lang.annotation


class PluginInfo(java.lang.annotation.Annotation, object):








    def annotationType(self) -> java.lang.Class: ...

    def category(self) -> unicode: ...

    def description(self) -> unicode: ...

    def equals(self, __a0: object) -> bool: ...

    def eventsConsumed(self) -> List[java.lang.Class]: ...

    def eventsProduced(self) -> List[java.lang.Class]: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def isSlowInstallation(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def packageName(self) -> unicode: ...

    def servicesProvided(self) -> List[java.lang.Class]: ...

    def servicesRequired(self) -> List[java.lang.Class]: ...

    def shortDescription(self) -> unicode: ...

    def status(self) -> ghidra.framework.plugintool.util.PluginStatus: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def slowInstallation(self) -> bool: ...
