import ghidra.program.model.address
import ghidra.program.model.listing
import java.lang


class MatchedData(object):








    def equals(self, __a0: object) -> bool: ...

    def getAData(self) -> ghidra.program.model.listing.Data: ...

    def getADataAddress(self) -> ghidra.program.model.address.Address: ...

    def getAMatchNum(self) -> int: ...

    def getAProgram(self) -> ghidra.program.model.listing.Program: ...

    def getBData(self) -> ghidra.program.model.listing.Data: ...

    def getBDataAddress(self) -> ghidra.program.model.address.Address: ...

    def getBMatchNum(self) -> int: ...

    def getBProgram(self) -> ghidra.program.model.listing.Program: ...

    def getClass(self) -> java.lang.Class: ...

    def getReason(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def AData(self) -> ghidra.program.model.listing.Data: ...

    @property
    def ADataAddress(self) -> ghidra.program.model.address.Address: ...

    @property
    def AMatchNum(self) -> int: ...

    @property
    def AProgram(self) -> ghidra.program.model.listing.Program: ...

    @property
    def BData(self) -> ghidra.program.model.listing.Data: ...

    @property
    def BDataAddress(self) -> ghidra.program.model.address.Address: ...

    @property
    def BMatchNum(self) -> int: ...

    @property
    def BProgram(self) -> ghidra.program.model.listing.Program: ...

    @property
    def reason(self) -> unicode: ...
